/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 model.glb -o ../src/Model_2023-07-31.tsx -t -p 5 -r . -TjDsS 
Files: model.glb [737.36MB] > model-transformed.glb [40.62MB] (94%)
*/

import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb');
  const zoomTo = props.zoomTo;
  return (
    <group {...props} dispose={null}>
      {/* <pointLight intensity={54.35141} decay={2} color="#ffb073" position={[3.80788, 2.45666, 1.36174]} rotation={[0, -1.38121, -Math.PI / 2]} scale={1.70216} />
      <pointLight intensity={1630.54239} decay={2} color="#b4b4ff" position={[8.11863, 2.31745, -2.34916]} rotation={[-Math.PI / 2, 0, 0]} scale={0.73403} /> */}
      <mesh
        receiveShadow
        geometry={nodes.car.geometry}
        material={materials.car}
        position={[8.68258, 3.10231, -2.57545]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.31879}
      />
      <mesh
        receiveShadow
        geometry={nodes.car001.geometry}
        material={materials.car}
        position={[3.14171, 3.30282, 0.57816]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.3207}
      />
      <mesh
        receiveShadow
        geometry={nodes.gd.geometry}
        material={materials.gd}
        position={[8.66246, 4.24255, -2.58625]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.64885}
      />
      <mesh
        receiveShadow
        geometry={nodes.mouse.geometry}
        material={materials.mouse}
        position={[6.79208, 3.07447, -2.56639]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.42449}
      />
      <mesh
        receiveShadow
        geometry={nodes.kiss.geometry}
        material={materials.kiss}
        position={[6.9835, 5.19715, -2.583]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.77752}
      />
      <mesh
        receiveShadow
        geometry={nodes.slay.geometry}
        material={materials.slay}
        position={[7.67088, 5.52231, -2.52059]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.79257}
      />
      <mesh
        receiveShadow
        geometry={nodes.tp.geometry}
        material={materials.tp}
        position={[8.72845, 3.51681, -2.58078]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.33809}
        onClick={(e) => zoomTo(e.object.position)}
      />
      <mesh
        receiveShadow
        geometry={nodes.no.geometry}
        material={materials.no}
        position={[6.70659, 4.45644, -2.58736]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.63196}
      />
      <mesh
        receiveShadow
        geometry={nodes.bt.geometry}
        material={materials.bt}
        position={[8.35606, 5.37967, -2.55057]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.75608}
      />
      <mesh
        receiveShadow
        geometry={nodes.bt002.geometry}
        material={materials.bt}
        position={[3.14113, 3.50459, -0.22804]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.70327}
      />
      <mesh
        receiveShadow
        geometry={nodes.sw.geometry}
        material={materials.sw}
        position={[8.68675, 4.96869, -2.5901]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.56253}
      />
      <mesh
        receiveShadow
        geometry={nodes.jp.geometry}
        material={materials.jp}
        position={[6.75816, 3.67476, -2.58645]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.63818}
      />
      <mesh
        receiveShadow
        geometry={nodes.s1.geometry}
        material={materials.s1}
        position={[3.74313, 2.65401, 2.41457]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.10466}
      />
      <mesh
        receiveShadow
        geometry={nodes.s2.geometry}
        material={materials.s2}
        position={[3.69714, 3.16084, 2.43927]}
        rotation={[Math.PI / 2, 0, 2.99541]}
        scale={0.10454}
      />
      <mesh
        receiveShadow
        geometry={nodes.s3.geometry}
        material={materials.s3}
        position={[3.45619, 2.648, 2.39472]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.1104}
      />
      <mesh
        receiveShadow
        geometry={nodes.s4.geometry}
        material={materials.s4}
        position={[3.91895, 2.50614, 2.31134]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.13482}
      />
      <mesh
        receiveShadow
        geometry={nodes.s6.geometry}
        material={materials.s6}
        position={[3.18308, 4.46701, 1.01733]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.10322}
      />
      <mesh
        receiveShadow
        geometry={nodes.s7.geometry}
        material={materials.s7}
        position={[3.17916, 4.45461, 2.07696]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.16676}
      />
      <mesh
        receiveShadow
        geometry={nodes.s9.geometry}
        material={materials.s9}
        position={[3.13857, 4.14361, 0.15102]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.55477}
      />
      <mesh
        receiveShadow
        geometry={nodes.s8.geometry}
        material={materials.s8}
        position={[3.17991, 4.38767, 1.72459]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.25699}
      />
      <mesh
        receiveShadow
        geometry={nodes.s10.geometry}
        material={materials.s10}
        position={[3.18088, 4.00607, 1.02472]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.14083}
      />
      <mesh
        receiveShadow
        geometry={nodes.s13.geometry}
        material={materials.s13}
        position={[3.1796, 3.96145, 2.60736]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11202}
      />
      <mesh
        receiveShadow
        geometry={nodes.s14.geometry}
        material={materials.s14}
        position={[3.17948, 4.63741, 2.7243]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11655}
      />
      <mesh
        receiveShadow
        geometry={nodes.s15.geometry}
        material={materials.s15}
        position={[3.14042, 5.3698, 1.95632]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.34233}
      />
      <mesh
        receiveShadow
        geometry={nodes.s16.geometry}
        material={materials.s16}
        position={[3.17912, 4.58025, 0.9556]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.16918}
      />
      <mesh
        receiveShadow
        geometry={nodes.s17.geometry}
        material={materials.s17}
        position={[3.16314, 4.60855, 0.66557]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.45761}
      />
      <mesh
        receiveShadow
        geometry={nodes.s18.geometry}
        material={materials.s18}
        position={[3.14409, 5.24566, 0.55501]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.14897}
      />
      <mesh
        receiveShadow
        geometry={nodes.s19.geometry}
        material={materials.s19}
        position={[3.13857, 4.98288, 1.092]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.24574}
      />
      <mesh
        receiveShadow
        geometry={nodes.s20.geometry}
        material={materials.s20}
        position={[3.14857, 4.1585, 3.01247]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.3021}
      />
      <mesh
        receiveShadow
        geometry={nodes.s21.geometry}
        material={materials.s21}
        position={[3.16128, 3.42561, 2.95971]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.58138}
      />
      <mesh
        receiveShadow
        geometry={nodes.s22.geometry}
        material={materials.s22}
        position={[3.14304, 5.24925, 0.84078]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.12267}
      />
      <mesh
        receiveShadow
        geometry={nodes.s23.geometry}
        material={materials.s23}
        position={[3.14944, 3.55906, 1.24915]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.33012}
      />
      <mesh
        receiveShadow
        geometry={nodes.s24.geometry}
        material={materials.s24}
        position={[3.17863, 4.51617, 1.14522]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.08372}
      />
      <mesh
        receiveShadow
        geometry={nodes.s26.geometry}
        material={materials.s26}
        position={[3.13972, 5.24544, 2.29889]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.14737}
      />
      <mesh
        receiveShadow
        geometry={nodes.s26001.geometry}
        material={materials.s26}
        position={[3.17866, 4.2377, 2.66681]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.12309}
      />
      <mesh
        receiveShadow
        geometry={nodes.s27.geometry}
        material={materials.s27}
        position={[3.1831, 4.00249, 2.22522]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.19294}
      />
      <mesh
        receiveShadow
        geometry={nodes.s28.geometry}
        material={materials.s28}
        position={[3.13953, 5.25952, 1.35765]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.22269}
      />
      <mesh
        receiveShadow
        geometry={nodes.s28001.geometry}
        material={materials.s28}
        position={[3.14186, 3.61693, 0.32456]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.22269}
      />
      <mesh
        receiveShadow
        geometry={nodes.s30.geometry}
        material={materials.s30}
        position={[3.13976, 5.54013, 2.28364]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.12814}
      />
      <mesh
        receiveShadow
        geometry={nodes.S31.geometry}
        material={materials.S31}
        position={[3.14218, 4.13257, 0.61675]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.22679}
      />
      <mesh
        receiveShadow
        geometry={nodes.S32.geometry}
        material={materials.S32}
        position={[3.13906, 3.85927, 3.00479]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.32741}
      />
      <mesh
        receiveShadow
        geometry={nodes.S33.geometry}
        material={materials.S33}
        position={[3.13917, 4.87822, 1.3664]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.18726}
      />
      <mesh
        receiveShadow
        geometry={nodes.S34.geometry}
        material={materials.S34}
        position={[3.14941, 3.65579, 2.29171]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.21258}
      />
      <mesh
        receiveShadow
        geometry={nodes.S35.geometry}
        material={materials.S35}
        position={[3.13874, 4.56472, 3.01225]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.21543}
      />
      <mesh
        receiveShadow
        geometry={nodes.S36001.geometry}
        material={materials.S36}
        position={[3.18012, 4.58735, 1.87074]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.16017}
      />
      <mesh
        receiveShadow
        geometry={nodes.S37.geometry}
        material={materials.S37}
        position={[3.18124, 4.50329, 1.36274]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.36542}
      />
      <mesh
        receiveShadow
        geometry={nodes.S38.geometry}
        material={materials.S38}
        position={[3.14615, 5.24697, 2.84428]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.29582}
      />
      <mesh
        receiveShadow
        geometry={nodes.S39.geometry}
        material={materials.S39}
        position={[3.14931, 5.07432, 2.50278]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.18892}
      />
      <mesh
        receiveShadow
        geometry={nodes.S40.geometry}
        material={materials.S40}
        position={[3.17801, 4.15785, 1.26631]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.40193}
      />
      <mesh
        receiveShadow
        geometry={nodes.S41.geometry}
        material={materials.S41}
        position={[3.14177, 4.86084, 1.90138]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.12231}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Quilted velvet coverlet black']}
        position={[6.54339, 0.95337, 1.36371]}
        scale={[2.27722, 1, 1.67521]}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.denmin_fabric_02}
        position={[8.48249, 1.90192, -2.15016]}
        rotation={[-1.71468, -0.98677, -1.15414]}
        scale={0.29401}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials['Flannel Yarn Dyed Plaid Fabric Red']}
        position={[8.46764, 1.82383, -1.83129]}
        scale={[0.27147, 0.39217, 0.38279]}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.fabric_pattern_07}
        position={[8.47839, 1.92612, -1.94537]}
        rotation={[-1.26548, 0.88326, 1.03371]}
        scale={0.2099}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials['Fabric 124']}
        position={[8.37082, 1.48234, -2.16015]}
        scale={[0.35879, 0.19238, 0.13932]}
      />
      <mesh
        receiveShadow
        geometry={nodes.s42.geometry}
        material={materials.s42}
        position={[3.17801, 4.31105, 2.00196]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.1158}
      />
      <mesh
        receiveShadow
        geometry={nodes.s43.geometry}
        material={materials.s43}
        position={[3.91804, 2.56447, 1.6568]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.09466, 0.06711, 0.09466]}
      />
      <mesh
        receiveShadow
        geometry={nodes.s44.geometry}
        material={materials.s44}
        position={[3.14226, 3.29706, 0.16005]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.23631}
      />
      <mesh
        receiveShadow
        geometry={nodes.s45.geometry}
        material={materials.s45}
        position={[3.78113, 2.6471, 1.69371]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={0.15217}
      />
      <mesh
        receiveShadow
        geometry={nodes.s46.geometry}
        material={materials.s46}
        position={[4.2398, 3.3232, 2.20719]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.10042}
      />
      <mesh
        receiveShadow
        geometry={nodes.s47.geometry}
        material={materials.s47}
        position={[3.91835, 2.57674, 2.44144]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.1073}
      />
      <mesh
        receiveShadow
        geometry={nodes.s48.geometry}
        material={materials.s48}
        position={[3.1384, 3.61918, 2.52934]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.09566}
      />
      <mesh
        receiveShadow
        geometry={nodes.s49.geometry}
        material={materials.s49}
        position={[3.15488, 3.24158, 0.94058]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.27584}
      />
      <mesh
        receiveShadow
        geometry={nodes.s50.geometry}
        material={materials.s50}
        position={[4.12181, 2.91566, 2.41184]}
        rotation={[1.57282, 0.04247, 2.64104]}
        scale={0.14448}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6328.geometry}
        material={materials.IMG_6328}
        position={[3.17811, 4.21493, 2.24099]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.19719}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6322.geometry}
        material={materials.IMG_6322}
        position={[3.18206, 4.24782, 2.11802]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.25676}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6317.geometry}
        material={materials.IMG_6317}
        position={[3.18765, 4.05477, 1.76667]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.30766}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6318.geometry}
        material={materials.IMG_6318}
        position={[3.19312, 4.31025, 2.47541]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.26188}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6319.geometry}
        material={materials.IMG_6319}
        position={[3.17802, 3.94741, 1.91363]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.18353}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6320.geometry}
        material={materials.IMG_6320}
        position={[3.18027, 4.19217, 1.48136]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.24075}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6321.geometry}
        material={materials.IMG_6321}
        position={[3.18241, 4.24949, 1.04024]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.33666}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6323.geometry}
        material={materials.IMG_6323}
        position={[3.14317, 3.87023, 0.71778]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.28662}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6324.geometry}
        material={materials.IMG_6324}
        position={[3.18572, 4.36286, 1.87167]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.24598}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6325.geometry}
        material={materials.IMG_6325}
        position={[3.18168, 4.41426, 2.32434]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11808}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6326.geometry}
        material={materials.IMG_6326}
        position={[3.1798, 4.12352, 1.96144]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.16073}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6327.geometry}
        material={materials.IMG_6327}
        position={[3.18087, 4.1025, 2.43766]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.10946}
      />
      <mesh
        receiveShadow
        geometry={nodes.shh1.geometry}
        material={materials.shh1}
        position={[3.14819, 4.03676, -0.26388]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.25987}
      />
      <mesh
        receiveShadow
        geometry={nodes.shh2.geometry}
        material={materials.shh2}
        position={[3.16375, 3.66606, -0.81325]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.87429}
      />
      <mesh
        receiveShadow
        geometry={nodes.shh3.geometry}
        material={materials.shh3}
        position={[7.71108, 3.65457, -2.58681]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={1.9586}
      />
      <mesh
        receiveShadow
        geometry={nodes.bedframe.geometry}
        material={materials.Wood}
        position={[6.69323, 1.56144, -0.76587]}
        rotation={[0, -0.01029, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[6.67822, 1.45324, -0.90649]}
        rotation={[0, -1.55913, 0]}
      />
      <mesh
        receiveShadow
        geometry={nodes.blanket.geometry}
        material={materials['Patchwork blanket for kids']}
        position={[6.67601, 2.64527, -0.51733]}
        rotation={[Math.PI, -1.54969, Math.PI]}
        scale={[1.08546, 1, 1.06053]}
      />
      <mesh
        receiveShadow
        geometry={nodes.pillow.geometry}
        material={materials['Lemon Patterned Flannel Fabric']}
        position={[6.24359, 2.26081, -2.18789]}
        rotation={[1.36138, 1.54682, -0.30257]}
        scale={[0.40586, 0.50992, 0.5265]}
      />
      <mesh
        receiveShadow
        geometry={nodes.pillow001.geometry}
        material={materials['Lemon Patterned Flannel Fabric']}
        position={[7.20789, 2.26615, -2.16032]}
        rotation={[2.03889, 1.4524, -0.93697]}
        scale={[0.40586, 0.50992, 0.50992]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Magnificent wood']}
        position={[5.06108, 4.14862, -2.69077]}
        rotation={[-Math.PI, 0.00161, 0]}
        scale={[-1.16779, -1.71969, -0.16649]}
      />
      <mesh
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials['Magnificent wood']}
        position={[3.8675, 2.36059, 1.31098]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[4.4119, 1.57665, 2.76811]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[3.31436, 1.57665, 2.7708]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[4.40926, 1.57665, -0.15694]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[3.31172, 1.57665, -0.15424]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[3.86641, 2.00654, 1.30195]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials['Magnificent wood']}
        position={[4.1292, 2.15817, 0.45037]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.33112, 0.09738, 0.49687]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[4.13078, 1.88732, 0.44723]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.33112, 0.15161, 0.49687]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.deskHandleU.geometry}
        material={materials.PaletteMaterial001}
        position={[4.50754, 2.15494, 0.44054]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.03542, 0.03243, 0.04108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.deskHandleD.geometry}
        material={materials.PaletteMaterial001}
        position={[4.50778, 1.88966, 0.45619]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.03542, 0.03243, 0.04108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.PaletteMaterial002}
        position={[4.47627, 2.15311, 0.44218]}
        rotation={[-Math.PI, -0.00212, -1.60063]}
        scale={[0.01284, 0.04716, 0.01618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.PaletteMaterial002}
        position={[4.44931, 1.88782, 0.45789]}
        rotation={[-Math.PI, -0.00212, -1.60063]}
        scale={[0.01284, 0.04716, 0.01618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chairLeatherTop.geometry}
        material={materials.fabric_leather_02}
        position={[5.89594, 2.56784, 2.10543]}
        rotation={[0, 1.07514, 0]}
        scale={0.68262}
      />
      <group
        position={[5.89286, 1.03172, 1.6781]}
        rotation={[-1.19132, -0.00911, -2.85383]}
        scale={[-0.0199, -0.02047, -0.02523]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials.PaletteMaterial003}
        />
      </group>
      <mesh
        receiveShadow
        geometry={nodes.compHead.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55351, 3.20897, 2.14689]}
        rotation={[0, 0.60667, 0]}
        scale={[0.36907, 0.41434, 0.5585]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bedside_body.geometry}
        material={materials.Wood}
        position={[8.36467, 1.55197, -2.30015]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={[0.26348, 0.40816, 0.4185]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bedisdeL3.geometry}
        material={materials.Wood}
        position={[8.71589, 0.88006, -2.49494]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bedsideL1.geometry}
        material={materials.Wood}
        position={[8.73389, 0.8845, -2.14167]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bedsideL2.geometry}
        material={materials.Wood}
        position={[8.02625, 0.8845, -2.11094]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bedsideL4.geometry}
        material={materials.Wood}
        position={[8.00825, 0.88006, -2.4642]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bedsideUpperDrawer.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[8.35211, 1.79047, -2.02549]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={[0.26348, 0.40816, 0.43626]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials.PaletteMaterial001}
        position={[8.34863, 1.45081, -1.63565]}
        rotation={[-Math.PI, 0.1198, -Math.PI]}
        scale={[0.26348, 0.40816, 0.4185]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials.Wood}
        position={[8.38147, 1.42412, -2.03714]}
        rotation={[-Math.PI, 1.52739, -Math.PI]}
        scale={[0.27387, 0.2299, 0.38256]}
      />
      <group
        position={[8.41348, 1.41693, -1.72333]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={0.02721}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere004.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere004_1.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>

      <group
        position={[8.73703, 2.08456, -2.16681]}
        rotation={[Math.PI, -1.38555, -Math.PI / 2]}
        scale={[-0.00385, -0.00927, -0.0144]}
      >
        //unfilled right side
        <mesh
          // castShadow
          // receiveShadow
          geometry={nodes.Plane063.geometry}
          material={materials.PaletteMaterial002}
        />
        //clock body
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane063_1.geometry}
          material={materials.PaletteMaterial002}
        />
        //top button
        <mesh
          // castShadow
          // receiveShadow
          geometry={nodes.Plane063_2.geometry}
          material={materials.PaletteMaterial002}
        />
        //middle clock divider
        <mesh
          // castShadow
          // receiveShadow
          geometry={nodes.Plane063_3.geometry}
          material={materials.PaletteMaterial004}
        ></mesh>
        //unfilled left side
        <mesh
          // castShadow
          // receiveShadow
          geometry={nodes.Plane063_4.geometry}
          material={materials.PaletteMaterial002}
        ></mesh>
        //filled right side
        <mesh
          // castShadow
          // receiveShadow
          geometry={nodes.Plane063_5.geometry}
          // material={materials.PaletteMaterial005}
        >
          <meshStandardMaterial color={'#ff0000'} />
        </mesh>
        //filled left side
        <mesh
          // castShadow
          // receiveShadow
          geometry={nodes.Plane063_6.geometry}
          material={materials.PaletteMaterial006}
        ></mesh>
      </group>
      <group
        position={[3.57264, 1.75082, -1.16755]}
        rotation={[-3.02039, -0.15262, -1.70998]}
      >
        <mesh
          
          geometry={nodes.Plane001_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          
         
          geometry={nodes.Plane001_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          
        
          geometry={nodes.Plane001_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          
          
          geometry={nodes.Plane001_4.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lowerBookshelf.geometry}
        material={materials.Wood}
        position={[3.39494, 4.18006, -1.25683]}
        scale={[0.302, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.upperBookshelf.geometry}
        material={materials.Wood}
        position={[3.35284, 4.76898, -0.88191]}
        scale={[0.302, 1, 1.36665]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.corkboard.geometry}
        material={materials['Cork natural']}
        position={[3.0905, 4.29743, 1.83965]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.45512, 1.17691, 0.96003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials['Old white plastic']}
        position={[4.25849, 2.43437, 1.26738]}
        rotation={[-Math.PI, 1.03639, -Math.PI]}
        scale={[0.08302, 0.02509, 0.10661]}
      />
      <group
        position={[3.58801, 4.33759, -1.42534]}
        scale={[0.06532, 0.08794, 0.08794]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_2.geometry}
          material={materials.PaletteMaterial008}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_7.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials['Magnificent wood']}
        position={[3.18556, 4.2879, 1.83277]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.04287, -0.4789, -0.99824]}
      />
      <group
        position={[3.50792, 2.60453, 1.00324]}
        rotation={[-3.13913, -0.48119, 0.00228]}
        scale={[0.08025, 0.16613, 0.16897]}
      >
        <mesh
          // castShadow
          receiveShadow
          geometry={nodes.Plane027_1.geometry}
          material={materials['notebook page']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027_2.geometry}
          material={materials.PaletteMaterial009}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pencilHolder.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55216, 2.4149, 0.37942]}
        scale={[0.10099, 0.13355, 0.1046]}
      />
      <group
        position={[3.59058, 2.59723, 0.40777]}
        rotation={[0.58743, 0.24553, 0.00029]}
        scale={[0.01057, 0.18126, 0.00912]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_6.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.58119, 2.58372, 0.37647]}
        rotation={[-0.6564, -0.25353, -0.34408]}
        scale={[0.01057, 0.18067, 0.00915]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_6.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.59058, 2.61444, 0.40777]}
        rotation={[0.41403, 0.10551, 0.00476]}
        scale={[0.01057, 0.18086, 0.00914]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_6.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>

      <group position={[3.47452, 4.83262, 0.14511]} scale={0.08426}>
        //lamp base
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials.PaletteMaterial010}
        />
        //lamp glass body
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials.PaletteMaterial011}
        >
          {' '}
        </mesh>
        //lamp balls
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_3.geometry}
          material={materials.PaletteMaterial012}
        >
          <meshStandardMaterial
            emissive='#ff00dd'
            emissiveIntensity={7.9}
            toneMapped={false}
          />
        </mesh>
      </group>

      <group
        position={[3.53106, 3.04255, 0.00858]}
        rotation={[0, 0.66379, 0]}
        scale={0.05772}
      >
        <mesh
          // castShadow
          receiveShadow
          geometry={nodes.Cylinder021.geometry}
          material={materials.PaletteMaterial001}
        />
        {/** Desk lamp lightbulb */}
        <mesh castShadow receiveShadow geometry={nodes.Cylinder021_1.geometry}>
          <meshStandardMaterial
            emissive='#cbc9b3'
            emissiveIntensity={2.8}
            toneMapped={false}
          />
        </mesh>
      </group>
      <group
        position={[3.55767, 2.63404, 0.8626]}
        rotation={[-3.13928, -0.3308, 0.00189]}
        scale={[0.08025, 0.16613, 0.16897]}
      >
        <mesh
          // castShadow
          receiveShadow
          geometry={nodes.Plane041_1.geometry}
          material={materials['notebook page']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041_2.geometry}
          material={materials.PaletteMaterial009}
        />
      </group>
      <mesh
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Basalt tiles.001']}
        position={[5.00147, 3.76926, -1.55381]}
        scale={[3.05, 2.855, 3.05]}
      />
      <mesh
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Worn Old Wood Planks']}
        position={[5.88322, 3.52281, 0.15419]}
        scale={[3.05, 2.855, 3.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Panels 02']}
        position={[8.38147, 1.42412, -2.03714]}
        rotation={[-Math.PI, 1.52739, -Math.PI]}
        scale={[0.27387, 0.2299, 0.38256]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials['Panels 02']}
        position={[8.35211, 1.79047, -2.02549]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={[0.26348, 0.40816, 0.43626]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials['Panels 02']}
        position={[4.1292, 2.15817, 0.45037]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      {/** Computer monitor screen */}
      {/**
       * TODO: figure out a different click-off
       * TODO: render sign-in form
       * TODO: make the sign-in form actually work
       * TODO: fix the evil sticker (decal?)
       * TODO: set up other zoom-tos (same onclick works, but need to figure out position offset)
       * TODO: clock material bloom
       * TODO: lose the effects composer sparks
       * TODO: bloom lava lamp
       * TODO: animate zoom
       * TODO: loading screen
       */}
      <mesh
        // castShadow
        // receiveShadow
        geometry={nodes.Cube017.geometry}
        position={[3.54909, 3.20587, 2.15376]}
        rotation={[0, 0.60667, 0]}
        scale={[0.36907, 0.41434, 0.5585]}
        onClick={(e) => zoomTo(e.object.position)}
      >
        <meshStandardMaterial
          emissive='#aefffc'
          emissiveIntensity={2}
          toneMapped={false}
        />
      </mesh>

      <group
        position={[4.34849, 2.42477, 2.02359]}
        rotation={[-3.13739, -0.11547, -3.07637]}
        scale={[0.22893, 0.29114, 0.54064]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane111.geometry}
          material={materials['Old white plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane111_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane111_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane111_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane111_4.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[3.85981, 2.35592, 1.28079]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shroomPotBookshelf.geometry}
        material={materials['Clay Base 01']}
        position={[3.43743, 4.92916, -1.86921]}
        scale={[0.10621, 0.09403, 0.10027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Panels 02']}
        position={[5.00147, 3.76926, -1.55381]}
        scale={[3.05, 2.855, 3.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM_Wood_doll.geometry}
        material={materials.Wood}
        position={[3.45513, 4.23683, -0.83844]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ball.geometry}
        material={materials.GolfBall}
        position={[4.0585, 2.44678, 2.6679]}
        rotation={[0, -0.41812, 0]}
        scale={1.73239}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Old_Book_Julius_Caesar_-_Shakespeare'].geometry}
        material={materials['Julius Caesar - Shakespeare']}
        position={[3.75239, 2.4248, 0.00975]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.86411}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Corner_table-02'].geometry}
        material={materials['Corner table -  wood']}
        position={[3.71639, 0.8998, -1.87044]}
        scale={1.97538}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mushroom_Lamp.geometry}
        material={materials.MI_DirtyPlastic13}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      <group
        position={[4.04818, 2.44681, 0.0184]}
        rotation={[Math.PI, -0.5292, Math.PI]}
        scale={-1.72073}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle051.geometry}
          material={materials.PaletteMaterial029}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle051_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['02'].geometry}
        material={materials.PaletteMaterial002}
        position={[3.18217, 3.96585, 1.55811]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <group
        position={[3.62783, 2.45315, 1.10553]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={1.57067}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186.geometry}
          material={materials['Burlington Leather']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186_3.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.6101, 2.54432, 1.15221]}
        rotation={[-Math.PI, 1.41977, Math.PI / 2]}
        scale={1.57067}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186.geometry}
          material={materials['Burlington Leather']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube186_3.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barbel_3Kg.geometry}
        material={materials.Fabric}
        position={[8.46874, 0.93661, -0.89506]}
        scale={1.35331}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barbel_3Kg001.geometry}
        material={materials.Fabric}
        position={[8.56466, 0.94828, -1.11225]}
        rotation={[0, -0.84164, 0]}
        scale={1.35331}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['3D_Lamborghini_Text_Logo002'].geometry}
        material={materials.PaletteMaterial002}
        position={[3.18274, 4.50822, 2.45234]}
        rotation={[1.81498, 0.09641, -1.58115]}
        scale={3.09965}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass_full_of_water.geometry}
        material={materials.PaletteMaterial018}
        position={[4.03297, 2.40889, 0.51335]}
        scale={2.10668}
      />
      <group
        position={[3.15731, 4.85772, 1.74468]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.2476, 0.29831, 0.2476]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert019.geometry}
          material={materials.PaletteMaterial037}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert019_1.geometry}
          material={materials.PaletteMaterial038}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert019_2.geometry}
          material={materials.PaletteMaterial038}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert019_3.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.13804, 3.57575, 1.92028]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.13792}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials['License plate']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['3'].geometry}
        material={materials.PaletteMaterial015}
        position={[8.03384, 1.24075, -1.91894]}
        rotation={[-1.4165, -0.08312, -1.48521]}
        scale={[0.51177, 0.30764, 0.44491]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.band.geometry}
        material={materials.PaletteMaterial016}
        position={[3.81175, 2.43534, 0.00486]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.band001.geometry}
        material={materials.PaletteMaterial016}
        position={[74.06784, 0, 105.70952]}
      />
      <group
        position={[3.81175, 2.43534, 0.00486]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials.PaletteMaterial017}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials.Body_2}
        />
      </group>
      <group position={[74.06784, 0, 105.70952]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials.PaletteMaterial017}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials.Body_2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.button.geometry}
        material={materials.PaletteMaterial002}
        position={[3.81175, 2.43534, 0.00486]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.button001.geometry}
        material={materials.PaletteMaterial002}
        position={[74.06784, 0, 105.70952]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cover_glass.geometry}
        material={materials.PaletteMaterial018}
        position={[3.81175, 2.43534, 0.00486]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cover_glass001.geometry}
        material={materials.PaletteMaterial018}
        position={[74.06784, 0, 105.70952]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass.geometry}
        material={materials.PaletteMaterial002}
        position={[3.81175, 2.4417, -0.04064]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass001.geometry}
        material={materials.PaletteMaterial002}
        position={[74.06784, 0, 105.70952]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.skew.geometry}
        material={materials.PaletteMaterial002}
        position={[3.81175, 2.4417, -0.04064]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.skew001.geometry}
        material={materials.PaletteMaterial002}
        position={[74.06784, 0, 105.70952]}
      />
      <group
        position={[3.47261, 4.32278, -0.47133]}
        rotation={[0, 1.0701, 0]}
        scale={[2.53676, 2.54191, 1.33795]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063.geometry}
          material={materials['Black metal']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_3.geometry}
          material={materials.PaletteMaterial019}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_4.geometry}
          material={materials['Black metal']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_7.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group position={[8.39408, 0.97776, 0.10381]} scale={1.78452}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003.geometry}
          material={materials['mustang-damen-schuhe-sneakers-Sole']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_1.geometry}
          material={materials['Innen sole']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_2.geometry}
          material={materials.PaletteMaterial020}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_3.geometry}
          material={materials.PaletteMaterial021}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_4.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_5.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_6.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_7.geometry}
          material={materials['leather 01.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_8.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_9.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_10.geometry}
          material={materials['Material.029']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_11.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_12.geometry}
          material={materials.Garn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_13.geometry}
          material={materials.Lasche}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_14.geometry}
          material={materials['leather 01.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_15.geometry}
          material={materials['schnürsenkel.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh003_16.geometry}
          material={materials.PaletteMaterial022}
        />
      </group>
      <group position={[8.20237, 0.98439, -0.0448]} scale={1.78452}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002.geometry}
          material={materials['mustang-damen-schuhe-sneakers-Sole.R']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_1.geometry}
          material={materials['Innen sole']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_2.geometry}
          material={materials.PaletteMaterial020}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_3.geometry}
          material={materials.PaletteMaterial021}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_4.geometry}
          material={materials['Innen sole.R']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_5.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_6.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_7.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_8.geometry}
          material={materials['leather 01.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_9.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_10.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_11.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_12.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_13.geometry}
          material={materials.Garn}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_14.geometry}
          material={materials.Lasche}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_15.geometry}
          material={materials['leather 01.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_16.geometry}
          material={materials.PaletteMaterial022}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_17.geometry}
          material={materials['schnürsenkel.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Object_08_-_Default_0002'].geometry}
        material={materials['Old white plastic']}
        position={[4.25852, 2.42165, 1.17342]}
        rotation={[-1.62409, 0.01567, 2.50065]}
        scale={0.0112}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Object_08_-_Default_0003'].geometry}
        material={materials['Old white plastic']}
        position={[3.70308, 2.44177, 1.79878]}
        rotation={[-1.75293, 0.30589, -2.48948]}
        scale={0.0112}
      />
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes['et_09_-_Default_0'].geometry}
        material={materials.PaletteMaterial002}
        position={[3.57872, 2.64754, 2.00447]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.01402}
      />
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes['et_09_-_Default_0001'].geometry}
        material={materials.PaletteMaterial002}
        position={[3.61117, 2.63709, 1.97267]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.01792}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.old_brick_01.geometry}
        material={materials['old brick 01']}
        position={[3.94816, 2.41821, 0.19684]}
        rotation={[0, -0.21626, 0]}
        scale={0.12317}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere000.geometry}
        material={materials.PaletteMaterial002}
        position={[3.45513, 4.23683, -0.83844]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body.geometry}
        material={materials.PaletteMaterial002}
        position={[3.77045, 2.41602, 0.2023]}
        rotation={[0, 0, 0.45167]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body001.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55067, 2.42356, 0.37151]}
        rotation={[Math.PI, -0.77363, -2.68992]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body002.geometry}
        material={materials.PaletteMaterial002}
        position={[3.60973, 2.42167, 0.42137]}
        rotation={[Math.PI, 1.36143, -2.68992]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body003.geometry}
        material={materials.PaletteMaterial002}
        position={[3.97601, 2.41249, 0.34514]}
        rotation={[0, -1.13182, 0.45167]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame.geometry}
        material={materials.PaletteMaterial002}
        position={[3.77011, 2.41484, 0.2023]}
        rotation={[0, 0, 0.45167]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame003.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55091, 2.42238, 0.37127]}
        rotation={[Math.PI, -0.77363, -2.68992]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame005.geometry}
        material={materials.PaletteMaterial002}
        position={[3.6098, 2.42049, 0.4217]}
        rotation={[Math.PI, 1.36143, -2.68992]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame007.geometry}
        material={materials.PaletteMaterial002}
        position={[3.97587, 2.41131, 0.34483]}
        rotation={[0, -1.13182, 0.45167]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame001.geometry}
        material={materials.PaletteMaterial002}
        position={[3.76931, 2.4165, 0.2023]}
        rotation={[0, 0, 0.45167]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame002.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55149, 2.42404, 0.37071]}
        rotation={[Math.PI, -0.77363, -2.68992]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame004.geometry}
        material={materials.PaletteMaterial002}
        position={[3.60997, 2.42214, 0.42249]}
        rotation={[Math.PI, 1.36143, -2.68992]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper_clip_body_frame006.geometry}
        material={materials.PaletteMaterial002}
        position={[3.97553, 2.41297, 0.3441]}
        rotation={[0, -1.13182, 0.45167]}
        scale={1.63684}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.peach_core.geometry}
        material={materials['Material.peach.core']}
        position={[4.19465, 2.43187, 0.25977]}
        rotation={[-0.70354, 0.02375, -1.56281]}
        scale={1.76926}
      />
      <group
        position={[3.40553, 4.24571, -1.99617]}
        rotation={[0, 0.82071, 0]}
        scale={2.00947}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder107.geometry}
          material={materials.DesertRoseSmallTex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder107_1.geometry}
          material={materials['Clay Base 01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder107_2.geometry}
          material={materials.stony_dirt_path}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Magnifier-Freepolyorg001'].geometry}
        material={materials['default']}
        position={[3.69662, 2.64861, 1.09]}
        rotation={[0, -0.76179, 0]}
        scale={0.85656}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials['Material.039']}
        position={[3.60163, 2.228, -1.85161]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials.stony_dirt_path}
        position={[3.60059, 2.14316, -1.85001]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.moneytreePot.geometry}
        material={materials['Circle_BAKED.001']}
        position={[3.60074, 2.10936, -1.8497]}
        scale={[1.29916, 1.53025, 1.29916]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath006.geometry}
        material={materials['Material.038']}
        position={[3.61807, 2.42117, -1.86375]}
        rotation={[-1.51978, 1.05233, 1.6531]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials['Material.037']}
        position={[3.77865, 2.35981, -1.96963]}
        rotation={[1.50987, 0.02704, -2.16043]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials['Material.037']}
        position={[3.67117, 2.46384, -1.95239]}
        rotation={[1.83052, 0.61123, -2.38185]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials['Material.037']}
        position={[3.79776, 2.43008, -1.93643]}
        rotation={[2.04051, 0.50464, -2.3719]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials['Material.037']}
        position={[3.73435, 2.42339, -1.69688]}
        rotation={[1.20614, -0.02991, -0.67295]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane039.geometry}
        material={materials['Material.037']}
        position={[3.55519, 2.42608, -2.0526]}
        rotation={[1.89173, 0.1787, 2.88149]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials['Material.037']}
        position={[3.49512, 2.53769, -1.98416]}
        rotation={[2.5596, -0.95511, 2.71001]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials['Material.037']}
        position={[3.60021, 2.49792, -1.76244]}
        rotation={[0.62134, 0.05717, 0.19473]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials['Material.037']}
        position={[3.53423, 2.3799, -1.69754]}
        rotation={[1.73452, 0.12227, 0.55037]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials['Material.037']}
        position={[3.48228, 2.28287, -1.90853]}
        rotation={[1.15812, 0.86717, 2.3324]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials['Material.037']}
        position={[3.38906, 2.35226, -1.81286]}
        rotation={[1.65039, 0.30997, 1.50351]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane037.geometry}
        material={materials['Material.037']}
        position={[3.52983, 2.32111, -2.07711]}
        rotation={[1.51212, -0.36231, 2.2686]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials['Material.037']}
        position={[3.75432, 2.48382, -1.99475]}
        rotation={[2.32624, 0.56447, -2.82227]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials['Material.037']}
        position={[3.59975, 2.40196, -1.67135]}
        rotation={[1.76674, 0.05717, 0.19473]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={materials['Material.037']}
        position={[3.68901, 2.48382, -1.65798]}
        rotation={[0.7203, 0.36972, -0.50434]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={materials['Material.037']}
        position={[3.40968, 2.4125, -1.73695]}
        rotation={[0.3248, -0.49114, 0.97391]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials['Material.037']}
        position={[3.661, 2.35226, -2.05907]}
        rotation={[1.25276, -0.03318, -2.85269]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane044.geometry}
        material={materials['Material.037']}
        position={[3.82052, 2.34781, -1.84367]}
        rotation={[1.92977, -0.45476, -1.52783]}
        scale={1.29916}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={materials['Material.037']}
        position={[3.82289, 2.45749, -1.85467]}
        rotation={[1.89784, 0.18765, -1.75438]}
        scale={1.29916}
      />
      <group
        position={[3.68874, 2.45666, 1.3846]}
        rotation={[-Math.PI / 2, 0, 1.76038]}
        scale={1.70216}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder112.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder112_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder112_2.geometry}
          material={materials.PaletteMaterial023}
        >
          <meshStandardMaterial
            emissive='#fff'
            emissiveIntensity={2}
            toneMapped={false}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder112_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder112_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder112_5.geometry}
          material={materials.PaletteMaterial024}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Handle.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55519, 2.45666, 1.41023]}
        rotation={[-Math.PI / 2, 0, 1.76038]}
        scale={1.70216}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp.geometry}
        material={nodes.Lamp.material}
        position={[3.79704, 2.45666, 1.36382]}
        rotation={[Math.PI, -0.18958, Math.PI / 2]}
        scale={1.70216}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Light_.geometry}
        material={materials.PaletteMaterial011}
        position={[3.80508, 2.45666, 1.36228]}
        rotation={[Math.PI, -0.18958, Math.PI]}
        scale={2.66782}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder058.geometry}
        material={materials.PaletteMaterial002}
        position={[3.8106, 2.45952, 1.36483]}
        rotation={[-2.25034, -0.12001, 1.84086]}
        scale={[0.01297, 0.12488, 0.00958]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder059.geometry}
        material={materials.PaletteMaterial002}
        position={[3.80958, 2.46085, 1.35952]}
        rotation={[-0.40761, 0.17438, 1.52263]}
        scale={[-0.01297, 0.12488, 0.00958]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder060.geometry}
        material={materials.PaletteMaterial002}
        position={[3.81029, 2.45272, 1.36319]}
        rotation={[2.73398, -0.17438, 1.37308]}
        scale={[-0.01297, 0.12488, 0.00958]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder061.geometry}
        material={materials.PaletteMaterial002}
        position={[3.80927, 2.45404, 1.35788]}
        rotation={[0.89125, 0.12001, 1.54662]}
        scale={[0.01297, 0.12488, 0.00958]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder062.geometry}
        material={materials.PaletteMaterial011}
        position={[3.80492, 2.45666, 1.36231]}
        rotation={[Math.PI, -0.18958, Math.PI / 2]}
        scale={0.4901}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Slider.geometry}
        material={materials.PaletteMaterial002}
        position={[3.74386, 2.47215, 1.34914]}
        rotation={[Math.PI, 1.38121, 1.7458]}
        scale={1.70216}
      />
      <group
        position={[8.00662, 1.2407, -1.44285]}
        rotation={[-Math.PI, -0.99781, -Math.PI]}
        scale={1.55689}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167.geometry}
          material={materials['bag_gray main']}
        />
        <mesh
          receiveShadow
          geometry={nodes.Cube167_1.geometry}
          material={materials['bag_dark gray']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_2.geometry}
          material={materials['bag_metal 1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_3.geometry}
          material={materials.bag_leather}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_4.geometry}
          material={materials['bag_metal 2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_5.geometry}
          material={materials.bag_plate}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_7.geometry}
          material={materials['bag_dark gray']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_8.geometry}
          material={materials.bag_zipper}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_9.geometry}
          material={materials['bag_metal 1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube167_10.geometry}
          material={materials['bag_metal 1']}
        />
      </group>
      <group
        position={[3.62164, 4.25735, -1.1163]}
        rotation={[-0.07961, -0.62025, 0.88003]}
        scale={1.41786}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle047.geometry}
        ></mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle047_1.geometry}
          material={materials.PaletteMaterial002}
        >
          <meshStandardMaterial
            emissive='#46ff74'
            emissiveIntensity={2}
            toneMapped={false}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle047_2.geometry}
          material={materials.PaletteMaterial002}
        >
          <meshStandardMaterial
            emissive='#46ff74'
            emissiveIntensity={2}
            toneMapped={false}
          />
        </mesh>
      </group>
      <group
        position={[3.97311, 2.43567, 1.41015]}
        rotation={[-2.75797, 1.14128, 2.70906]}
        scale={2.55779}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Data_Widowmaker_Eyes_Iris002.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Data_Widowmaker_Eyes_Iris002_1.geometry}
          material={materials.PaletteMaterial018}
        />
      </group>


      //desk shhroom
      <group
        position={[3.72422, 2.66768, 0.90818]}
        rotation={[-1.14963, -0.22253, 0.32676]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049.geometry}
          material={materials.PaletteMaterial025}
        >
          <meshStandardMaterial
            emissive='#ff0000'
            emissiveIntensity={8}
            toneMapped={false}
            color={'#ff0000'}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049_1.geometry}
          material={materials['Stiel.001']}
        ></mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049_2.geometry}
          material={materials.Lammelleln}
        ></mesh>
      </group>


      <group
        position={[3.92422, 2.00068, -1.990]}
        rotation={[-1.54963, -1.99253, 3.42676]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049.geometry}
          material={materials.PaletteMaterial025}
        >
          <meshStandardMaterial
            emissive='#ff0000'
            emissiveIntensity={10}
            toneMapped={false}
            color={'#ff0000'}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049_1.geometry}
          material={materials['Stiel.001']}
        ></mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049_2.geometry}
          material={materials.Lammelleln}
        ></mesh>
      </group>


      <group
        position={[8.01947, 2.0281, -2.10942]}
        rotation={[0.0761, -0.14554, 0.01106]}
        scale={1.32359}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.comb11.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.comb11_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.comb11_2.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group position={[3.29815, 4.8224, -0.73617]} scale={[1.39397, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube170.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube170_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube170_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube170_3.geometry}
          material={materials.PaletteMaterial026}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube170_4.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Input.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Marshall_Logo.geometry}
        material={materials.PaletteMaterial002}
        position={[3.42373, 4.98199, -0.73617]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1, 1.39397, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Off.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.On.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tone.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Volume.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wire.geometry}
        material={materials.PaletteMaterial002}
        position={[3.21901, 5.0224, -0.73617]}
        scale={[1.39397, 1, 1]}
      />
      <group position={[3.43748, 5.00924, -1.86565]}>
        //bookshelf shroom hat
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve.geometry}
          material={materials.PaletteMaterial028}
        >
          <meshStandardMaterial
            emissive='#ff0000'
            emissiveIntensity={8}
            toneMapped={false}
            color={'#ff0000'}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_1.geometry}
          material={materials['Stiel.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_2.geometry}
          material={materials['Lammelleln.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_3.geometry}
          material={materials['Stiel.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_4.geometry}
          material={materials['Stiel.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_5.geometry}
          material={materials['boden.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM_MushroomLamp01001.geometry}
        material={materials.MI_DirtyPlastic12}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM_MushroomLamp01002.geometry}
        material={materials.PaletteMaterial016}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM_MushroomLamp01003.geometry}
        material={materials.MI_LightLED01}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      <group
        position={[8.15868, 2.04951, -2.34039]}
        rotation={[-3.05675, 1.50357, 3.01958]}
        scale={1.96894}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube173.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube173_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[8.15279, 2.12907, -2.32849]}
        rotation={[-0.25874, 1.53441, 0.22203]}
        scale={1.96894}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube175.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube175_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[8.15821, 2.0918, -2.33561]}
        rotation={[-0.12389, 1.46416, 0.08756]}
        scale={1.96894}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube176.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube176_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[4.04818, 2.44681, 0.0184]}
        rotation={[0, 0.5292, -Math.PI]}
        scale={[-1.72073, 1.72073, 1.72073]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle052.geometry}
          material={materials.PaletteMaterial029}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle052_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.13927, 3.63483, 0.73964]}
        rotation={[Math.PI / 2, -0.0304, -Math.PI / 2]}
        scale={0.14963}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104.geometry}
          material={materials.PaletteMaterial030}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_1.geometry}
          material={materials.PaletteMaterial031}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_2.geometry}
          material={materials.PaletteMaterial032}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_7.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_8.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_9.geometry}
          material={materials.PaletteMaterial033}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane104_10.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group position={[4.03297, 2.40662, 0.51335]} scale={2.10668}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035.geometry}
          material={materials.PaletteMaterial034}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035_1.geometry}
          material={materials.PaletteMaterial034}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere508.geometry}
        material={materials.PaletteMaterial034}
        position={[4.03297, 2.40662, 0.51335]}
        scale={2.10668}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Harley_Davidson_riders_only_old.geometry}
        material={materials['Material_-_Aufgeblasene_Vorderseite_Ebene_2']}
        position={[3.13573, 4.91201, 2.81922]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cardboard_Box_SQ01001.geometry}
        material={materials['Cardboard Box SQ01']}
        position={[3.6504, 0.7176, -0.56535]}
        scale={1.66594}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cardboard_Box_SQ01002.geometry}
        material={materials['Cardboard Box SQ01']}
        position={[3.52548, 1.21166, -0.51556]}
      />
      <group
        position={[3.17977, 4.2564, 1.60464]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.33019}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.1551, 4.41998, 0.08593]}
        rotation={[-Math.PI, 1.51315, -Math.PI]}
        scale={0.46844}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano001.geometry}
          material={materials.PaletteMaterial035}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano001_1.geometry}
          material={materials.PaletteMaterial036}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano001_2.geometry}
          material={materials.PaletteMaterial035}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Texto.geometry}
        material={materials.PaletteMaterial036}
        position={[3.17964, 4.45165, 0.11668]}
        rotation={[-1.96761, 1.46988, 1.62514]}
        scale={0.38781}
      />
      <group
        position={[3.13975, 4.95735, 2.28716]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.65739}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clavicle_right_.geometry}
        material={materials.PaletteMaterial002}
        position={[3.48899, 5.30871, -0.17955]}
        rotation={[0, -1.39626, Math.PI]}
        scale={0.32303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.PaletteMaterial002}
        position={[3.48899, 5.26225, -0.17955]}
        rotation={[-Math.PI, 1.39626, -Math.PI]}
        scale={0.32303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.PaletteMaterial002}
        position={[3.48899, 5.14034, -0.17955]}
        rotation={[0, -1.39626, Math.PI]}
        scale={0.32303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.femur_right_.geometry}
        material={materials.PaletteMaterial002}
        position={[3.48899, 5.30871, -0.17955]}
        rotation={[-Math.PI, 1.39626, -Math.PI]}
        scale={0.32303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pelvis.geometry}
        material={materials.PaletteMaterial002}
        position={[3.48899, 5.12315, -0.17955]}
        rotation={[0, -1.39626, Math.PI]}
        scale={0.32303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.teeth_upper.geometry}
        material={materials.PaletteMaterial002}
        position={[3.48899, 5.34473, -0.17955]}
        rotation={[-0.58148, -1.36284, 2.57007]}
        scale={0.32303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CURTAIN_2007.geometry}
        material={materials['Fabric 01']}
        position={[5.8758, 3.79651, -2.40374]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[-0.57735, 1, 2.08315]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CURTAIN_2008.geometry}
        material={materials['Fabric 01']}
        position={[3.94105, 3.7957, -2.40374]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.78135, 1, 2.08315]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.PaletteMaterial002}
        position={[4.90591, 6.04884, -2.39933]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[1, 1.24289, 1.55954]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.Wood}
        position={[4.90591, 6.04885, -2.40031]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.24289, 1, 1]}
      />
      <group position={[3.41903, 4.83103, -0.36294]} scale={2.68371}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube187.geometry}
          material={materials.paper}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube187_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube187_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube187_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube187_4.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <instancedMesh
        args={[nodes.Cube171.geometry, materials.PaletteMaterial027, 5]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Cube171.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Sphere001.geometry, materials.PaletteMaterial007, 24]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Sphere001.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Sphere001_1.geometry, materials.PaletteMaterial002, 24]}
        castShadow
        receiveShadow
        instanceMatrix={nodes.Sphere001_1.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload('/model-transformed.glb');
