/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 render_fin.glb -o src/Model_Test_4.jsx -p 5 -r . -TjDsS 
Files: render_fin.glb [596.93MB] > render_fin-transformed.glb [28.96MB] (95%)
*/

import {
  useContext,
  useEffect,
  useRef,
  useState,
  useLayoutEffect,
  lazy,
  Suspense,
} from 'react';
import { useNavigate } from 'react-router-dom';
import {
  useGLTF,
  Plane,
  Html,
  Billboard,
  MeshTransmissionMaterial,
  Caustics,
  useDetectGPU,
  Text3D,
  Svg,
} from '@react-three/drei';
import { DoubleSide } from 'three';

import escButton from '/svg/esc_button.svg';
import arrow from '/svg/arrow_login.svg';
import { GlobalContext, LandingContext } from '../../lib/context';
import SignInHelperText from './SignInHelperText';

const Screensaver = lazy(() => import('../Screensaver'));

export default function Model(props) {
  const { nodes, materials } = useGLTF('/render_fin-transformed.glb');

  const navigate = useNavigate();

  const globalContext = useContext(GlobalContext);
  const landingContext = useContext(LandingContext);
  const escBtnRef = useRef(null);
  const screenRef = useRef(null);
  const newMeetingRef = useRef(null);
  const corkboardRef = useRef(null);
  const stingRef = useRef(null);
  const desktopRef = useRef(null);
  const shelvesRef = useRef(null);
  const bedsideTableRef = useRef(null);
  const [isSignHelperHidden, setIsSignHelperHidden] = useState(true);

  useLayoutEffect(() => {
    // console.log('setting layers');
    for (let object of [
      newMeetingRef,
      corkboardRef,
      screenRef,
      escBtnRef,
      stingRef,
      desktopRef,
      shelvesRef,
      bedsideTableRef,
    ]) {
      if (object.current?.layers) {
        object.current.layers.enable(1);
      }
    }
  }, []);

  const gpu = useDetectGPU();

  useEffect(() => {
    setTimeout(() => {
      setIsSignHelperHidden(false);
    }, 8000);
  }, []);

  useEffect(() => {
    if (globalContext.isSignedIn) {
      if (
        landingContext.isZoomed &&
        landingContext.targetLabel === 'newMeetingTunnelZoom'
      ) {
        console.log('zooming');
        navigate('/tunnel');
      }
    }
  }, [landingContext.targetLabel, globalContext.isSignedIn]);


  return (
    <group {...props} dispose={null}>
      {/** Computer monitor screen */}
      <mesh
        // geometry={nodes.Cube017.geometry}
        position={[3.54909, 3.20587, 2.15376]}
        rotation={[0, 0.60667, 0]}
        scale={[0.36907, 0.41434, 0.5585]}
      >
        <Plane
          args={[1.5, 1.5]}
          rotation={[0, Math.PI / 2, 0]}
          position={[1.45, 0, 0]}
        >
          <meshStandardMaterial
            emissive='#5DC0EA'
            emissiveIntensity={3.5}
            toneMapped={false}
          />
        </Plane>

        {landingContext.signInHintIsVisible && !isSignHelperHidden && (
          <>
            <SignInHelperText />
            <Svg
              src={arrow}
              scale={0.13}
              position={[1.5, 1.1, 2.1]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <meshStandardMaterial
                emissive='#00FFCC'
                emissiveIntensity={40}
                toneMapped={false}
              />
            </Svg>
          </>
        )}
        <Plane
          args={[0.6, 0.12]}
          position={[1.56, -0.83, 0.5]}
          rotation={[0, Math.PI / 2, 0]}
          ref={escBtnRef}
          onClick={() => {
            if (landingContext.targetLabel === 'monitor')
              landingContext.releaseZoom();
            else return;
          }}
        >
          <meshBasicMaterial color={'#ff0000'} transparent opacity={0} />
        </Plane>
        <Billboard
          // position={[5.54909, 3.20587, 3.95376]}
          position={[1.5, -0.8, 0.6]}
          rotation={[0, 0, 0]}
          visible={landingContext.targetLabel === 'monitor'}
          follow={true}
          lockX={true}
          lockY={true}
          lockZ={true}
        >
          <Text3D
            rotation={[0, Math.PI / 2, 0]}
            position={[0, -0.05, 0.18]}
            height={0.01}
            fontSize={0.005}
            size={0.02}
            // lineHeight={0.5}
            letterSpacing={0.003}
            // position={[-5.34909, 3.20587, 4.25376]}
            color='#00FFCC'
            outlineColor='#fff'
            outlineOffsetY='20'
            outlineWidth={30}
            // size={0.001}
            font='/fonts/Press Start 2P_Regular.json'
          >
            click
            <meshStandardMaterial
              emissive='#16c7a4'
              emissiveIntensity={1.9}
              toneMapped={false}
            />
          </Text3D>
          <Svg
            src={escButton}
            scale={0.009}
            rotation={[0, Math.PI / 2, 0]}

            // position={[3.54909, 3.20587, 3.95376]}
          />
          <Text3D
            rotation={[0, Math.PI / 2, 0]}
            position={[0, -0.05, -0.1]}
            height={0.01}
            fontSize={0.005}
            size={0.02}
            color='#00FFCC'
            outlineColor='fff'
            outlineWidth='3px'
            letterSpacing={0.003}
            font='/fonts/Press Start 2P_Regular.json'
          >
            to exit
            <meshStandardMaterial
              emissive='#16c7a4'
              emissiveIntensity={1.9}
              toneMapped={false}
            />
          </Text3D>
        </Billboard>

        <Html
          ref={screenRef}
          as='div'
          distanceFactor={0.5}
          position={[1.4599, -0.04, -0.01]}
          transform={true}
          occlude='raycast'
          sprite={false}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.67, 1.14, 0.11]}
        >
          <GlobalContext.Provider value={globalContext}>
            <LandingContext.Provider value={landingContext}>
              <Suspense fallback={null}>
                <Screensaver />
              </Suspense>
            </LandingContext.Provider>
          </GlobalContext.Provider>
        </Html>
      </mesh>
      {/**rug */}
      <mesh
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Quilted velvet coverlet black']}
        position={[6.54339, 0.95337, 1.36371]}
        scale={[2.27722, 1, 1.67521]}
      />
      {/**drawer cloth */}
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.denmin_fabric_02}
        position={[8.48249, 1.90192, -2.15016]}
        rotation={[-1.71468, -0.98677, -1.15414]}
        scale={0.29401}
      />
      {/**drawer cloth */}
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials['Flannel Yarn Dyed Plaid Fabric Red']}
        position={[8.46764, 1.82383, -1.83129]}
        scale={[0.27147, 0.39217, 0.38279]}
      />
      {/**drawer cloth */}
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials.fabric_pattern_07}
        position={[8.47839, 1.92612, -1.94537]}
        rotation={[-1.26548, 0.88326, 1.03371]}
        scale={0.2099}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials['Fabric 124']}
        position={[8.37082, 1.48234, -2.16015]}
        scale={[0.35879, 0.19238, 0.13932]}
      />
      {/**wooden doll */}
      <mesh
        geometry={nodes.bedframe.geometry}
        material={materials.Wood}
        position={[6.69323, 1.56144, -0.74012]}
        rotation={[0, -0.01029, 0]}
      />
      {/**mattress */}
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[6.7053, 1.82504, -0.74779]}
        rotation={[0, -1.55913, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.blanket.geometry}
        material={materials['Patchwork blanket for kids']}
        position={[6.67601, 2.64527, -0.49158]}
        rotation={[Math.PI, -1.54969, Math.PI]}
        scale={[1.08546, 1, 1.06053]}
      />
      <mesh
        castShadow
        geometry={nodes.pillow.geometry}
        material={materials['Lemon Patterned Flannel Fabric']}
        position={[6.24359, 2.26081, -2.16214]}
        rotation={[1.36138, 1.54682, -0.30257]}
        scale={[0.40586, 0.50992, 0.5265]}
      />
      <mesh
        castShadow
        geometry={nodes.pillow001.geometry}
        material={materials['Lemon Patterned Flannel Fabric']}
        position={[7.20789, 2.26615, -2.13458]}
        rotation={[2.03889, 1.4524, -0.93697]}
        scale={[0.40586, 0.50992, 0.50992]}
      />
      {/**window frame */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Magnificent wood']}
        position={[5.06108, 4.13997, -2.7071]}
        rotation={[-Math.PI, 0.00161, 0]}
        scale={[-1.16779, -1.71969, -0.16649]}
      />
      {/**desktop */}
      <mesh
        ref={desktopRef}
        onClick={() => landingContext.zoomToObject('desktop')}
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials['Magnificent wood']}
        position={[3.8675, 2.36059, 1.31098]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      {/**desk leg */}
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials['Magnificent wood']}
        position={[4.4119, 1.57665, 2.76811]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      {/**desk leg */}
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials['Magnificent wood']}
        position={[4.40926, 1.57665, -0.15694]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      {/**desk leg */}
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials['Magnificent wood']}
        position={[3.31436, 1.57665, 2.7708]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      {/**desk leg */}
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials['Magnificent wood']}
        position={[3.31172, 1.57665, -0.15424]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.05329, 0.74066, 0.07404]}
      />
      {/**desk body */}
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials['Magnificent wood']}
        position={[3.86641, 2.00654, 1.30195]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      {/**desk top drawer */}
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials['Magnificent wood']}
        position={[4.1292, 2.15817, 0.45037]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.33112, 0.09738, 0.49687]}
      />
      {/**desk bottom drawer */}
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials['Magnificent wood']}
        position={[4.13078, 1.88732, 0.44723]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.33112, 0.15161, 0.49687]}
      />
      {/**desk top handle */}
      <mesh
        geometry={nodes.deskHandleU.geometry}
        material={materials.PaletteMaterial001}
        position={[4.50754, 2.15494, 0.44054]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.03542, 0.03243, 0.04108]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.PaletteMaterial002}
        position={[4.47627, 2.15311, 0.44218]}
        rotation={[-Math.PI, -0.00212, -1.60063]}
        scale={[0.01284, 0.04716, 0.01618]}
      />
      <mesh
        geometry={nodes.deskHandleD.geometry}
        material={materials.PaletteMaterial001}
        position={[4.50778, 1.88966, 0.45619]}
        rotation={[Math.PI, -0.00212, Math.PI]}
        scale={[0.03542, 0.03243, 0.04108]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials.PaletteMaterial002}
        position={[4.44931, 1.88782, 0.45789]}
        rotation={[-Math.PI, -0.00212, -1.60063]}
        scale={[0.01284, 0.04716, 0.01618]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chairLeatherTop.geometry}
        material={materials.fabric_leather_02}
        position={[5.89594, 2.56784, 2.10543]}
        rotation={[0, 1.07514, 0]}
        scale={0.68262}
      />
      <group
        position={[5.89286, 1.04272, 1.6781]}
        rotation={[-1.22332, -0.00711, -2.85383]}
        scale={[-0.0199, -0.02047, -0.02523]}
      >
        {/**chair stand metal */}
        <mesh
          castShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials.PaletteMaterial002}
        />
        {/**chair wheels */}
        <mesh
          castShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials.PaletteMaterial003}
        />
      </group>
      <mesh
        receiveShadow
        geometry={nodes.compHead.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55351, 3.20897, 2.14689]}
        rotation={[0, 0.60667, 0]}
        scale={[0.36907, 0.41434, 0.5585]}
      />
      {/**nightstand body */}
      <mesh
        castShadow
        geometry={nodes.bedside_body.geometry}
        material={materials.Wood}
        position={[8.36467, 1.55197, -2.30015]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={[0.26348, 0.40816, 0.4185]}
      />
      <mesh
        geometry={nodes.bedisdeL3.geometry}
        material={materials.Wood}
        position={[8.71589, 0.88006, -2.49494]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        geometry={nodes.bedsideL1.geometry}
        material={materials.Wood}
        position={[8.73389, 0.8845, -2.14167]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        geometry={nodes.bedsideL2.geometry}
        material={materials.Wood}
        position={[8.02625, 0.8845, -2.11094]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        geometry={nodes.bedsideL4.geometry}
        material={materials.Wood}
        position={[8.00825, 0.88006, -2.4642]}
        rotation={[-2.40743, 1.53593, 2.42855]}
        scale={[0.18318, 0.28376, 0.29094]}
      />
      <mesh
        castShadow
        geometry={nodes.bedsideUpperDrawer.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[8.35211, 1.79047, -2.02549]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={[0.26348, 0.40816, 0.43626]}
      />
      {/**nightstand upper handle */}
      <mesh
        geometry={nodes.Cube046.geometry}
        material={materials.PaletteMaterial001}
        position={[8.34863, 1.45081, -1.63565]}
        rotation={[-Math.PI, 0.1198, -Math.PI]}
        scale={[0.26348, 0.40816, 0.4185]}
      />
      {/**green shhrom on the shelf */}
      <mesh
        geometry={nodes.Cube047.geometry}
        material={materials.Wood}
        position={[8.38147, 1.42412, -2.03714]}
        rotation={[-Math.PI, 1.52739, -Math.PI]}
        scale={[0.27387, 0.2299, 0.38256]}
      />
      {/**nightstand bottom handle */}
      <group
        position={[8.41348, 1.41693, -1.72333]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={0.02721}
      >
        <mesh
          geometry={nodes.Sphere004.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.Sphere004_1.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>

      {/**skateboard */}
      <group
        position={[3.57264, 1.75082, -1.16755]}
        rotation={[-3.02039, -0.15262, -1.70998]}
      >
        <mesh
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Fabric}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials.PaletteMaterial002}
        />
        {/**skateboard trucks */}
        <mesh
          geometry={nodes.Plane001_3.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.lowerBookshelf.geometry}
        material={materials['Magnificent wood']}
        position={[3.39494, 4.18006, -1.25683]}
        scale={[0.302, 1, 1]}
      />
      <mesh
        castShadow
        geometry={nodes.upperBookshelf.geometry}
        material={materials['Magnificent wood']}
        position={[3.35284, 4.76898, -0.88191]}
        scale={[0.302, 1, 1.36665]}
      />
      <mesh
        ref={corkboardRef}
        onClick={() => {
          landingContext.zoomToObject('corkboard');
        }}
        receiveShadow
        geometry={nodes.corkboard.geometry}
        material={materials['Cork natural']}
        position={[3.0905, 4.29743, 1.83965]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.45512, 1.17691, 0.96003]}
      />
      <group
        position={[3.23174, 4.03593, 1.64712]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.01653}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere001.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.18963, 4.29856, 1.47946]}
        rotation={[0.13278, 0.18097, -1.12154]}
        scale={0.00917}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere001.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.20559, 4.52949, 2.10692]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.01019}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere006.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere006_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**mouse */}
      <mesh
        castShadow
        geometry={nodes.Cube020.geometry}
        material={materials['Old white plastic']}
        position={[4.25849, 2.43437, 1.26738]}
        rotation={[-Math.PI, 1.03639, -Math.PI]}
        scale={[0.08302, 0.02509, 0.10661]}
      />
      {/**rubs cube */}
      <group
        position={[3.58801, 4.33759, -1.42534]}
        scale={[0.06532, 0.08794, 0.08794]}
      >
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.Cube013_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube013_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube013_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube013_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube013_7.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**corkboard frame */}
      <mesh
        castShadow
        geometry={nodes.Cube022.geometry}
        material={materials['Magnificent wood']}
        position={[3.18556, 4.2879, 1.83277]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.04287, -0.4789, -0.99824]}
      />
      {/**notebooks */}
      <group
        position={[3.50792, 2.60453, 1.00324]}
        rotation={[-3.13913, -0.48119, 0.00228]}
        scale={[0.08025, 0.16613, 0.16897]}
      >
        <mesh
          geometry={nodes.Plane027.geometry}
          material={materials['notebook page']}
        />
        <mesh
          geometry={nodes.Plane027_1.geometry}
          material={materials.PaletteMaterial006}
        />
      </group>
      {/**pencil holder */}
      <mesh
        geometry={nodes.pencilHolder.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55216, 2.4149, 0.37942]}
        scale={[0.10099, 0.13355, 0.1046]}
      />
      {/**pencil */}
      <group
        position={[3.59058, 2.59723, 0.40777]}
        rotation={[0.58743, 0.24553, 0.00029]}
        scale={[0.01057, 0.18126, 0.00912]}
      >
        <mesh
          geometry={nodes.Cylinder013.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder013_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder013_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder013_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder013_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**pencil */}
      <group
        position={[3.58119, 2.58372, 0.37647]}
        rotation={[-0.6564, -0.25353, -0.34408]}
        scale={[0.01057, 0.18067, 0.00915]}
      >
        <mesh
          geometry={nodes.Cylinder014.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder014_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder014_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder014_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder014_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder014_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**pencil */}
      <group
        position={[3.59058, 2.61444, 0.40777]}
        rotation={[0.41403, 0.10551, 0.00476]}
        scale={[0.01057, 0.18086, 0.00914]}
      >
        <mesh
          geometry={nodes.Cylinder015.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder015_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder015_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder015_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder015_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder015_5.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**lavalamp */}
      <group position={[3.47452, 4.83262, 0.14511]} scale={0.08426}>
        <mesh
          geometry={nodes.Circle_1.geometry}
          material={materials.PaletteMaterial007}
        />
        {/* //lamp glass body */}
        <mesh
          geometry={nodes.Circle_2.geometry}
          material={materials.PaletteMaterial008}
        />
        {/* //lamp balls */}
        <mesh
          geometry={nodes.Circle_3.geometry}
          material={materials.PaletteMaterial009}
        >
          <meshStandardMaterial
            emissive='#ff00dd'
            emissiveIntensity={7.9}
            toneMapped={false}
          />
        </mesh>
      </group>
      <group
        position={[3.53106, 3.04255, 0.00858]}
        rotation={[0, 0.66379, 0]}
        scale={0.05772}
      >
        <mesh
          geometry={nodes.Cylinder021.geometry}
          material={materials.PaletteMaterial001}
        />
        {/** Desk lamp lightbulb */}
        <mesh
          geometry={nodes.Cylinder021_1.geometry}
          material={materials.PaletteMaterial002}
        >
          <meshStandardMaterial
            emissive='#cbc9b3'
            emissiveIntensity={7.8}
            toneMapped={false}
          />
        </mesh>
      </group>
      <group
        position={[3.55767, 2.63404, 0.8626]}
        rotation={[-3.13928, -0.3308, 0.00189]}
        scale={[0.08025, 0.16613, 0.16897]}
      >
        <mesh
          receiveShadow
          geometry={nodes.Plane041.geometry}
          material={materials['notebook page']}
        />
        <mesh
          geometry={nodes.Plane041_1.geometry}
          material={materials.PaletteMaterial006}
        />
      </group>
      {/**walls */}
      <mesh
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Basalt tiles.001']}
        position={[5.00147, 3.76926, -1.55381]}
        scale={[3.05, 2.855, 3.05]}
      />
      {/**floors */}
      <mesh
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Worn Old Wood Planks']}
        position={[5.88322, 3.52281, 0.15419]}
        scale={[3.05, 2.855, 3.05]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials['Magnificent wood']}
        position={[8.38147, 1.42412, -2.03714]}
        rotation={[-Math.PI, 1.52739, -Math.PI]}
        scale={[0.27387, 0.2299, 0.38256]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Magnificent wood']}
        position={[8.35211, 1.79047, -2.02549]}
        rotation={[-Math.PI, 1.5274, -Math.PI]}
        scale={[0.26348, 0.40816, 0.43626]}
      />
      {/**desk top drawer */}
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['Magnificent wood']}
        position={[4.1292, 2.15817, 0.45037]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      {/**keyboard */}
      <group
        position={[4.34849, 2.42477, 2.02359]}
        rotation={[-3.13739, -0.11547, -3.07637]}
        scale={[0.22893, 0.29114, 0.54064]}
      >
        <mesh
          castShadow
          geometry={nodes.Plane111.geometry}
          material={materials['Old white plastic']}
        />
        <mesh
          geometry={nodes.Plane111_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Plane111_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Plane111_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Plane111_4.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Dark oak fine wood texture']}
        position={[3.85981, 2.35592, 1.28079]}
        rotation={[Math.PI, -0.00212, Math.PI]}
      />
      <mesh
        geometry={nodes.shroomPotBookshelf.geometry}
        material={materials['Clay Base 01']}
        position={[3.43743, 4.92916, -1.86921]}
        scale={[0.10621, 0.09403, 0.10027]}
      />
      <group
        position={[3.20426, 3.99994, 2.61497]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00861}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere003.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere003_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.22435, 4.07088, 2.21676]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.01019}
      >
        <mesh
          geometry={nodes.Sphere003.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Sphere003_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.1857, 4.67312, 2.69903]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00265}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere007.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere007_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**wall panels */}
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Panels 02']}
        position={[5.00147, 3.76926, -1.55381]}
        scale={[3.05, 2.855, 3.05]}
      />
      <group
        position={[3.21822, 4.33378, 1.15938]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.01312}
      >
        {/**sphere pin section */}
        <mesh
          castShadow
          geometry={nodes.Sphere008.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere008_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.24643, 4.66264, 1.47275]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.01653}
      >
        {/**sphere pin section */}
        <mesh
          castShadow
          geometry={nodes.Sphere009.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere009_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.21276, 4.64922, 1.86975]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.01019}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere010.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere010_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.19595, 4.28194, 2.61684]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00656}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere012.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere012_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.21737, 4.4245, 2.48133]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00861}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere016.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere016_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.21707, 4.45701, 2.35133]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00861}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere017.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere017_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.21832, 4.15445, 2.46355]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00702}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere018.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere018_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.21788, 4.29919, 2.20498]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00861}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere019.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere019_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.19492, 4.35729, 2.15349]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00861}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere020.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere020_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.20247, 4.18452, 1.99964]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00702}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere023.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere023_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sphere pin section */}
      <group
        position={[3.20124, 4.01295, 1.89344]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.00702}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere024.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere024_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[3.22232, 4.46798, 1.86714]}
        rotation={[-0.27206, -0.04861, -1.73041]}
        scale={0.01019}
      >
        <mesh
          castShadow
          geometry={nodes.Sphere028.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          geometry={nodes.Sphere028_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.SM_Wood_doll.geometry}
        material={materials['Magnificent wood']}
        position={[3.45513, 4.23683, -0.83844]}
        rotation={[0, Math.PI / 2, 0]}
      />
      {/**golfball */}
      <mesh
        geometry={nodes.Ball.geometry}
        material={materials.GolfBall}
        position={[4.0585, 2.44678, 2.6679]}
        rotation={[0, -0.41812, 0]}
        scale={1.73239}
      />
      <mesh
        geometry={nodes['Old_Book_Julius_Caesar_-_Shakespeare'].geometry}
        material={materials['Julius Caesar - Shakespeare']}
        position={[3.75239, 2.4248, 0.00975]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.86411}
      />
      {/**paper clips */}
      <mesh
        geometry={nodes.Paper_clip_plastic.geometry}
        material={materials.PaletteMaterial021}
        position={[3.72476, 2.64987, 1.11974]}
        rotation={[Math.PI, -0.80144, Math.PI]}
        scale={3.17474}
      />
      <mesh
        geometry={nodes.Paper_clip_plastic001.geometry}
        material={materials.PaletteMaterial021}
        position={[3.60538, 2.61993, 1.24513]}
        rotation={[0, -0.27212, 0]}
        scale={3.17474}
      />
      <mesh
        geometry={nodes.Paper_clip_plastic002.geometry}
        material={materials.PaletteMaterial021}
        position={[3.63965, 2.65426, 1.10079]}
        rotation={[Math.PI, -0.80144, Math.PI]}
        scale={3.17474}
      />
      <mesh
        geometry={nodes.Paper_clip_plastic003.geometry}
        material={materials.PaletteMaterial021}
        position={[4.03443, 2.41305, 0.75398]}
        rotation={[0, -0.27212, 0]}
        scale={3.17474}
      />
      <mesh
        geometry={nodes.Paper_clip_plastic004.geometry}
        material={materials.PaletteMaterial021}
        position={[4.02602, 2.411, 0.72695]}
        rotation={[0, -0.75643, 0]}
        scale={3.17474}
      />
      {/**corner table */}
      <mesh
        geometry={nodes['Corner_table-02'].geometry}
        material={materials['Magnificent wood']}
        position={[3.71639, 0.8998, -1.87044]}
        scale={1.97538}
      />
      {/**shhroom lamp base */}
      <mesh
        geometry={nodes.Mushroom_Lamp.geometry}
        material={materials.MI_DirtyPlastic13}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      {/**scissors right half */}
      <group
        position={[4.04818, 2.44681, 0.0184]}
        rotation={[Math.PI, -0.5292, Math.PI]}
        scale={-1.72073}
      >
        <mesh
          geometry={nodes.Circle051.geometry}
          material={materials.PaletteMaterial023}
        />
        <mesh
          geometry={nodes.Circle051_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**folder bottom */}
      <group
        position={[3.62783, 2.45315, 1.10553]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={1.57067}
      >
        <mesh
          geometry={nodes.Cube186.geometry}
          material={materials['Burlington Leather']}
        />
        <mesh
          geometry={nodes.Cube186_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube186_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube186_3.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**folder top */}
      <group
        position={[3.6101, 2.54432, 1.15221]}
        rotation={[-Math.PI, 1.41977, Math.PI / 2]}
        scale={1.57067}
      >
        {/**folder body */}
        <mesh
          receiveShadow
          geometry={nodes.Cube027.geometry}
          material={materials['Burlington Leather']}
        />
        <mesh
          geometry={nodes.Cube027_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube027_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube027_3.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**barbels */}
      <mesh
        castShadow
        geometry={nodes.Barbel_3Kg.geometry}
        material={materials.Fabric}
        position={[8.46874, 0.95661, -0.89506]}
        scale={1.35331}
      />
      <mesh
        castShadow
        geometry={nodes.Barbel_3Kg001.geometry}
        material={materials.Fabric}
        position={[8.56466, 0.97828, -1.11225]}
        rotation={[0, -0.84164, 0]}
        scale={1.35331}
      />
      {/**lambo sign */}
      <mesh
        geometry={nodes['3D_Lamborghini_Text_Logo002'].geometry}
        material={materials.PaletteMaterial002}
        position={[3.18274, 4.50822, 2.45234]}
        rotation={[1.81498, 0.09641, -1.58115]}
        scale={3.09965}
      />
      {/**skeleton */}
      <mesh
        geometry={nodes.collar001.geometry}
        material={materials.bone}
        position={[3.4654, 5.30794, -0.22676]}
        rotation={[0, 1.57053, 0]}
        scale={0.32097}
      />
      <mesh
        geometry={nodes['3'].geometry}
        material={materials.PaletteMaterial010}
        position={[8.03384, 1.24075, -1.91894]}
        rotation={[-1.4165, -0.08312, -1.48521]}
        scale={[0.51177, 0.30764, 0.44491]}
      />
      {/**wrist watch */}
      <group
        position={[3.81175, 2.43534, 0.00486]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      >
        <mesh
          geometry={nodes.Plane007.geometry}
          material={materials.PaletteMaterial011}
        />
        <mesh
          geometry={nodes.Plane007_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Plane007_2.geometry}
          material={materials.PaletteMaterial012}
        />
        <mesh
          geometry={nodes.Plane007_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Plane007_4.geometry}
          material={materials.PaletteMaterial013}
        />
        <mesh
          geometry={nodes.Plane007_5.geometry}
          material={materials.Body_2}
        />
      </group>
      <mesh
        geometry={nodes.skew.geometry}
        material={materials.PaletteMaterial002}
        position={[3.81175, 2.4417, -0.04064]}
        rotation={[0.03023, -0.30773, 0.03963]}
        scale={3.36323}
      />
      {/**film camera */}
      <group
        position={[3.47261, 4.32278, -0.47133]}
        rotation={[0, 1.0701, 0]}
        scale={[2.53676, 2.54191, 1.33795]}
      >
        <mesh
          geometry={nodes.Cube063.geometry}
          material={materials['Black metal']}
        />
        <mesh
          geometry={nodes.Cube063_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube063_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube063_3.geometry}
          material={materials.PaletteMaterial014}
        />
        <mesh
          receiveShadow
          geometry={nodes.Cube063_4.geometry}
          material={materials['Black metal']}
        />
        <mesh
          geometry={nodes.Cube063_5.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube063_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube063_7.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**sneakers */}
      <group position={[8.39408, 0.97776, 0.10381]} scale={1.78452}>
        <mesh
          castShadow
          geometry={nodes.mesh003.geometry}
          material={materials['mustang-damen-schuhe-sneakers-Sole']}
        />
        <mesh
          geometry={nodes.mesh003_1.geometry}
          material={materials['Innen sole']}
        />
        <mesh
          geometry={nodes.mesh003_2.geometry}
          material={materials.PaletteMaterial015}
        />
        <mesh
          geometry={nodes.mesh003_3.geometry}
          material={materials.PaletteMaterial016}
        />
        <mesh
          geometry={nodes.mesh003_4.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          receiveShadow
          geometry={nodes.mesh003_5.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          geometry={nodes.mesh003_6.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          geometry={nodes.mesh003_7.geometry}
          material={materials['leather 01.004']}
        />
        <mesh
          geometry={nodes.mesh003_8.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          geometry={nodes.mesh003_9.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          geometry={nodes.mesh003_10.geometry}
          material={materials['Material.029']}
        />
        <mesh
          receiveShadow
          geometry={nodes.mesh003_11.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh geometry={nodes.mesh003_12.geometry} material={materials.Garn} />
        <mesh
          geometry={nodes.mesh003_13.geometry}
          material={materials.Lasche}
        />
        <mesh
          geometry={nodes.mesh003_14.geometry}
          material={materials['leather 01.008']}
        />
        <mesh
          receiveShadow
          geometry={nodes.mesh003_15.geometry}
          material={materials['schnürsenkel.004']}
        />
        <mesh
          geometry={nodes.mesh003_16.geometry}
          material={materials.PaletteMaterial017}
        />
      </group>
      <group position={[8.20237, 0.98439, -0.0448]} scale={1.78452}>
        <mesh
          castShadow
          geometry={nodes.mesh002.geometry}
          material={materials['mustang-damen-schuhe-sneakers-Sole.R']}
        />
        <mesh
          geometry={nodes.mesh002_1.geometry}
          material={materials['Innen sole']}
        />
        <mesh
          geometry={nodes.mesh002_2.geometry}
          material={materials.PaletteMaterial015}
        />
        <mesh
          geometry={nodes.mesh002_3.geometry}
          material={materials.PaletteMaterial016}
        />
        <mesh
          geometry={nodes.mesh002_4.geometry}
          material={materials['Innen sole.R']}
        />
        <mesh
          geometry={nodes.mesh002_5.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          receiveShadow
          geometry={nodes.mesh002_6.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          geometry={nodes.mesh002_7.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          geometry={nodes.mesh002_8.geometry}
          material={materials['leather 01.004']}
        />
        <mesh
          geometry={nodes.mesh002_9.geometry}
          material={materials['leather 01.005']}
        />
        <mesh
          geometry={nodes.mesh002_10.geometry}
          material={materials.Innenfuter}
        />
        <mesh
          geometry={nodes.mesh002_11.geometry}
          material={materials['Material.023']}
        />
        <mesh
          geometry={nodes.mesh002_12.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh geometry={nodes.mesh002_13.geometry} material={materials.Garn} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh002_14.geometry}
          material={materials.Lasche}
        />
        <mesh
          geometry={nodes.mesh002_15.geometry}
          material={materials['leather 01.008']}
        />
        <mesh
          geometry={nodes.mesh002_16.geometry}
          material={materials.PaletteMaterial017}
        />
        <mesh
          receiveShadow
          geometry={nodes.mesh002_17.geometry}
          material={materials['schnürsenkel.004']}
        />
      </group>
      {/**comp wire right */}
      <mesh
        geometry={nodes['Object_08_-_Default_0002'].geometry}
        material={materials['Old white plastic']}
        position={[4.25852, 2.42165, 1.17342]}
        rotation={[-1.62409, 0.01567, 2.50065]}
        scale={0.0112}
      />
      {/**comp wire left */}
      <mesh
        geometry={nodes['Object_08_-_Default_0003'].geometry}
        material={materials['Old white plastic']}
        position={[3.70308, 2.44177, 1.79878]}
        rotation={[-1.75293, 0.30589, -2.48948]}
        scale={0.0112}
      />
      {/**comp bottom support */}
      <mesh
        castShadow
        geometry={nodes['et_09_-_Default_0'].geometry}
        material={materials.PaletteMaterial002}
        position={[3.57872, 2.64754, 2.00447]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.01402}
      />
      {/**comp mid support */}
      <mesh
        castShadow
        geometry={nodes['et_09_-_Default_0001'].geometry}
        material={materials.PaletteMaterial002}
        position={[3.61117, 2.63709, 1.97267]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.01792}
      />
      {/**elastic */}
      <mesh
        castShadow
        geometry={nodes.old_brick_01.geometry}
        material={materials['old brick 01']}
        position={[3.94816, 2.41821, 0.19684]}
        rotation={[0, -0.21626, 0]}
        scale={0.12317}
      />
      <mesh
        castShadow
        geometry={nodes.Sphere000.geometry}
        material={materials.PaletteMaterial002}
        position={[3.45513, 4.23683, -0.83844]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Paper_clip_body.geometry}
        material={materials.PaletteMaterial002}
        position={[3.77045, 2.41602, 0.2023]}
        rotation={[0, 0, 0.45167]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body001.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55067, 2.42356, 0.37151]}
        rotation={[Math.PI, -0.77363, -2.68992]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body002.geometry}
        material={materials.PaletteMaterial002}
        position={[3.60973, 2.42167, 0.42137]}
        rotation={[Math.PI, 1.36143, -2.68992]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body003.geometry}
        material={materials.PaletteMaterial002}
        position={[3.97601, 2.41249, 0.34514]}
        rotation={[0, -1.13182, 0.45167]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame.geometry}
        material={materials.PaletteMaterial002}
        position={[3.77011, 2.41484, 0.2023]}
        rotation={[0, 0, 0.45167]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame001.geometry}
        material={materials.PaletteMaterial002}
        position={[3.76931, 2.4165, 0.2023]}
        rotation={[0, 0, 0.45167]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame002.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55149, 2.42404, 0.37071]}
        rotation={[Math.PI, -0.77363, -2.68992]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame003.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55091, 2.42238, 0.37127]}
        rotation={[Math.PI, -0.77363, -2.68992]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame004.geometry}
        material={materials.PaletteMaterial002}
        position={[3.60997, 2.42214, 0.42249]}
        rotation={[Math.PI, 1.36143, -2.68992]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame005.geometry}
        material={materials.PaletteMaterial002}
        position={[3.6098, 2.42049, 0.4217]}
        rotation={[Math.PI, 1.36143, -2.68992]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame006.geometry}
        material={materials.PaletteMaterial002}
        position={[3.97553, 2.41297, 0.3441]}
        rotation={[0, -1.13182, 0.45167]}
        scale={1.63684}
      />
      <mesh
        geometry={nodes.Paper_clip_body_frame007.geometry}
        material={materials.PaletteMaterial002}
        position={[3.97587, 2.41131, 0.34483]}
        rotation={[0, -1.13182, 0.45167]}
        scale={1.63684}
      />
      <mesh
        castShadow
        geometry={nodes.peach_core.geometry}
        material={materials['Material.peach.core']}
        position={[4.19465, 2.43187, 0.25977]}
        rotation={[-0.70354, 0.02375, -1.56281]}
        scale={1.76926}
      />
      {/** shelf succulent */}
      <group
        position={[3.40553, 4.24571, -1.99617]}
        rotation={[0, 0.82071, 0]}
        scale={2.00947}
      >
        <mesh
          receiveShadow
          geometry={nodes.Cylinder107.geometry}
          material={materials.DesertRoseSmallTex}
        />
        <mesh
          receiveShadow
          geometry={nodes.Cylinder107_1.geometry}
          material={materials['Clay Base 01']}
        />
        <mesh
          geometry={nodes.Cylinder107_2.geometry}
          material={materials.stony_dirt_path}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes['Magnifier-Freepolyorg001'].geometry}
        material={materials['default']}
        position={[3.69662, 2.64861, 1.09]}
        rotation={[0, -0.76179, 0]}
        scale={0.85656}
      />
      <mesh
        geometry={nodes.Circle006.geometry}
        material={materials.stony_dirt_path}
        position={[3.60059, 2.14316, -1.85001]}
        scale={1.29916}
      />
      {/**money tree */}
      <group
        position={[3.67117, 2.46384, -1.95239]}
        rotation={[1.83052, 0.61123, -2.38185]}
        scale={1.29916}
      >
        <mesh
          geometry={nodes.Plane081.geometry}
          material={materials['Material.037']}
        />
        <mesh
          geometry={nodes.Plane081_1.geometry}
          material={materials['Material.038']}
        />
        <mesh
          geometry={nodes.Plane081_2.geometry}
          material={materials['Material.039']}
        />
        <mesh
          geometry={nodes.Plane081_3.geometry}
          material={materials['Circle_BAKED.001']}
        />
      </group>
      {/**flashlight */}
      <group
        position={[3.68874, 2.45666, 1.3846]}
        rotation={[-Math.PI / 2, 0, 1.76038]}
        scale={1.70216}
      >
        {/**body */}
        <mesh
          castShadow
          geometry={nodes.Cylinder112.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder112_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder112_2.geometry}
          material={materials.PaletteMaterial018}
        />
        <mesh
          geometry={nodes.Cylinder112_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder112_4.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cylinder112_5.geometry}
          material={materials.PaletteMaterial019}
        />
      </group>
      <mesh
        geometry={nodes.Handle.geometry}
        material={materials.PaletteMaterial002}
        position={[3.55519, 2.45666, 1.41023]}
        rotation={[-Math.PI / 2, 0, 1.76038]}
        scale={1.70216}
      />
      <mesh
        geometry={nodes.Lamp.geometry}
        material={nodes.Lamp.material}
        position={[3.79704, 2.45666, 1.36382]}
        rotation={[Math.PI, -0.18958, Math.PI / 2]}
        scale={1.70216}
      />
      <mesh
        geometry={nodes.Light_.geometry}
        material={materials.PaletteMaterial008}
        position={[3.80508, 2.45666, 1.36228]}
        rotation={[Math.PI, -0.18958, Math.PI]}
        scale={2.66782}
      />
      <mesh
        geometry={nodes.Cylinder058.geometry}
        material={materials.PaletteMaterial002}
        position={[3.8106, 2.45952, 1.36483]}
        rotation={[-2.25034, -0.12001, 1.84086]}
        scale={[0.01297, 0.12488, 0.00958]}
      />
      <mesh
        geometry={nodes.Cylinder059.geometry}
        material={materials.PaletteMaterial002}
        position={[3.80958, 2.46085, 1.35952]}
        rotation={[-0.40761, 0.17438, 1.52263]}
        scale={[-0.01297, 0.12488, 0.00958]}
      />
      <mesh
        geometry={nodes.Cylinder060.geometry}
        material={materials.PaletteMaterial002}
        position={[3.81029, 2.45272, 1.36319]}
        rotation={[2.73398, -0.17438, 1.37308]}
        scale={[-0.01297, 0.12488, 0.00958]}
      />
      <mesh
        geometry={nodes.Cylinder061.geometry}
        material={materials.PaletteMaterial002}
        position={[3.80927, 2.45404, 1.35788]}
        rotation={[0.89125, 0.12001, 1.54662]}
        scale={[0.01297, 0.12488, 0.00958]}
      />
      <mesh
        geometry={nodes.Cylinder062.geometry}
        material={materials.PaletteMaterial008}
        position={[3.80492, 2.45666, 1.36231]}
        rotation={[Math.PI, -0.18958, Math.PI / 2]}
        scale={0.4901}
      />
      <mesh
        geometry={nodes.Slider.geometry}
        material={materials.PaletteMaterial002}
        position={[3.74386, 2.47215, 1.34914]}
        rotation={[Math.PI, 1.38121, 1.7458]}
        scale={1.70216}
      />
      {/**backpack */}
      <group
        position={[8.00662, 1.2407, -1.44285]}
        rotation={[-Math.PI, -0.99781, -Math.PI]}
        scale={1.55689}
      >
        {/**body bottom */}
        <mesh
          castShadow
          geometry={nodes.Cube167.geometry}
          material={materials['bag_gray main']}
        />
        <mesh
          geometry={nodes.Cube167_1.geometry}
          material={materials['bag_dark gray']}
        />
        <mesh
          geometry={nodes.Cube167_2.geometry}
          material={materials['bag_metal 1']}
        />
        <mesh
          geometry={nodes.Cube167_3.geometry}
          material={materials.bag_leather}
        />
        <mesh
          geometry={nodes.Cube167_4.geometry}
          material={materials['bag_metal 2']}
        />
        <mesh
          geometry={nodes.Cube167_6.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube167_8.geometry}
          material={materials.bag_zipper}
        />
      </group>
      {/* //green glow shhroom */}
      <group
        position={[3.62164, 4.25735, -1.1163]}
        rotation={[-0.07961, -0.62025, 0.88003]}
        scale={1.41786}
      >
        <mesh
          geometry={nodes.Circle047.geometry}
          material={materials.PaletteMaterial002}
        />
        {/**hat */}
        <mesh
          geometry={nodes.Circle047_1.geometry}
          material={materials.PaletteMaterial002}
        >
          <meshStandardMaterial
            emissive='#46ff74'
            emissiveIntensity={3}
            toneMapped={false}
          />
        </mesh>
        <mesh
          geometry={nodes.Circle047_2.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**eyeball */}
      <group
        position={[3.97311, 2.43567, 1.41015]}
        rotation={[-2.75797, 1.14128, 2.70906]}
        scale={2.55779}
      >
        <mesh
          geometry={nodes.Data_Widowmaker_Eyes_Iris002.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          geometry={nodes.Data_Widowmaker_Eyes_Iris002_1.geometry}
          material={materials.PaletteMaterial012}
        />
      </group>
      {/**harmonica */}
      <group
        position={[8.01947, 2.0281, -2.10942]}
        rotation={[0.0761, -0.14554, 0.01106]}
        scale={1.32359}
      >
        <mesh
          geometry={nodes.comb11.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.comb11_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.comb11_2.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**speaker */}
      <group position={[3.29815, 4.8224, -0.73617]} scale={[1.39397, 1, 1]}>
        <mesh
          geometry={nodes.Cube170.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube170_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube170_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube170_3.geometry}
          material={materials.PaletteMaterial020}
        />
        <mesh
          geometry={nodes.Cube170_4.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.Input.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      {/**speaker logo */}
      <mesh
        geometry={nodes.Marshall_Logo.geometry}
        material={materials.PaletteMaterial002}
        position={[3.42373, 4.98199, -0.73617]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[1, 1.39397, 1]}
      />
      <mesh
        geometry={nodes.Off.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        geometry={nodes.On.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        geometry={nodes.Tone.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        geometry={nodes.Volume.geometry}
        material={materials.PaletteMaterial002}
        position={[3.23311, 4.8224, -0.72312]}
        scale={[1.39397, 1, 1]}
      />
      <mesh
        geometry={nodes.Wire.geometry}
        material={materials.PaletteMaterial002}
        position={[3.21901, 5.0224, -0.73617]}
        scale={[1.39397, 1, 1]}
      />
      {/**red shhroom shelf */}
      <group position={[3.43748, 5.00924, -1.86565]}>
        <mesh
          geometry={nodes.BezierCurve.geometry}
          material={materials.PaletteMaterial022}
        >
          <meshStandardMaterial
            emissive='#ff0000'
            emissiveIntensity={10}
            toneMapped={false}
            color={'#ff0000'}
          />
        </mesh>
        <mesh
          geometry={nodes.BezierCurve_1.geometry}
          material={materials['Stiel.003']}
        />
        <mesh
          geometry={nodes.BezierCurve_2.geometry}
          material={materials['Lammelleln.001']}
        />
        <mesh
          geometry={nodes.BezierCurve_3.geometry}
          material={materials['Stiel.004']}
        />
        <mesh
          geometry={nodes.BezierCurve_4.geometry}
          material={materials['Stiel.005']}
        />
        <mesh
          geometry={nodes.BezierCurve_5.geometry}
          material={materials['boden.001']}
        />
      </group>
      {/**shhroom lamp */}
      {/**head */}
      <mesh
        geometry={nodes.SM_MushroomLamp01001.geometry}
        material={materials.MI_DirtyPlastic12}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      {/**bulb */}
      <mesh
        geometry={nodes.SM_MushroomLamp01002.geometry}
        material={materials.PaletteMaterial011}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      {/**body */}
      <mesh
        geometry={nodes.SM_MushroomLamp01003.geometry}
        material={materials.MI_LightLED01}
        position={[8.11863, 2.15597, -2.34916]}
        scale={0.73403}
      />
      {/**books nightstand */}
      <group
        position={[8.15868, 2.04951, -2.34039]}
        rotation={[-3.05675, 1.50357, 3.01958]}
        scale={1.96894}
      >
        <mesh
          geometry={nodes.Cube173.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube173_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube173_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube173_3.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**scissors circle left half */}
      <group
        position={[4.04818, 2.44681, 0.0184]}
        rotation={[0, 0.5292, -Math.PI]}
        scale={[-1.72073, 1.72073, 1.72073]}
      >
        <mesh
          geometry={nodes.Circle052.geometry}
          material={materials.PaletteMaterial023}
        />
        <mesh
          geometry={nodes.Circle052_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      {/**curtain right */}
      <mesh
        castShadow
        geometry={nodes.CURTAIN_01001.geometry}
        material={materials['olive fabric']}
        position={[4.15322, 3.85594, -2.38999]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[-0.81528, 1.43726, 2.05712]}
      />
      {/**curtain left */}
      <mesh
        geometry={nodes.CURTAIN_02001.geometry}
        material={materials['olive fabric']}
        position={[6.23756, 3.86585, -2.39566]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.85695, 1.43726, 2.05712]}
      />
      {/**curtain rod hooks */}
      <mesh
        geometry={nodes.hook.geometry}
        material={materials.PaletteMaterial002}
        position={[5.15512, 6.07979, -2.42162]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={1.43726}
      />
      {/**curtin rod */}
      <mesh
        geometry={nodes.metal_rod.geometry}
        material={materials.Wood}
        position={[5.15512, 6.07981, -2.39539]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={1.43726}
      />
      <mesh
        castShadow
        geometry={nodes.Drinking_Glass_Model003.geometry}
        material={materials.PaletteMaterial008}
        position={[4.21799, 2.40663, 0.56561]}
        scale={1.81398}
      />
      {/**books on the shelf */}
      <group position={[3.41903, 4.83103, -0.36294]} scale={2.68371}>
        <mesh geometry={nodes.Cube187.geometry} material={materials.paper} />
        <mesh
          receiveShadow
          geometry={nodes.Cube187_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube187_2.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          receiveShadow
          geometry={nodes.Cube187_3.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.Cube187_4.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <instancedMesh
        args={[nodes.Sphere005.geometry, materials.PaletteMaterial004, 6]}
        instanceMatrix={nodes.Sphere005.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Sphere005_1.geometry, materials.PaletteMaterial002, 6]}
        instanceMatrix={nodes.Sphere005_1.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload('/render_fin-transformed.glb');
