/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 shhrooms.glb -o src/ShroomsMoodel.jsx -p 5 -r . -TjDsS 
Files: shhrooms.glb [825.6KB] > shhrooms-transformed.glb [311.24KB] (62%)
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shhrooms-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <group
        position={[3.72422, 2.66768, 0.90818]}
        rotation={[-1.14963, -0.22253, 0.32676]}
      >
        <mesh
          geometry={nodes.Circle049.geometry}
          material={materials['hut.001']}
        >
          <meshStandardMaterial
            emissive='#ff0000'
            emissiveIntensity={10}
            toneMapped={false}
            color={'#ff0000'}
          />
        </mesh>
        <mesh
          castShadow
          geometry={nodes.Circle049_1.geometry}
          material={materials['Stiel.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle049_2.geometry}
          material={materials.Lammelleln}
        />
      </group>
      <group
        position={[3.99816, 2.00646, -1.7006]}
        rotation={[-1.15113, -0.2071, 0.31969]}
      >
        <mesh
          geometry={nodes.Circle002.geometry}
          material={materials['hut.001']}
        >
          <meshStandardMaterial
            emissive='#ff0000'
            emissiveIntensity={10}
            toneMapped={false}
            color={'#ff0000'}
          />
        </mesh>
        <mesh
          geometry={nodes.Circle002_1.geometry}
          material={materials['Stiel.001']}
        />
        <mesh
          geometry={nodes.Circle002_2.geometry}
          material={materials.Lammelleln}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/shhrooms-transformed.glb');
