/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 wall_art.glb -o src/WallArt.jsx -p 5 -r . -TjDsS 
Files: wall_art.glb [64.02MB] > wall_art-transformed.glb [4.11MB] (94%)
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/wall_art-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.car002.geometry}
        material={materials.car}
        position={[8.68258, 3.10231, -2.58347]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.31879}
      />
      <mesh
        receiveShadow
        geometry={nodes.car001.geometry}
        material={materials.car}
        position={[3.14171, 3.28239, 0.58402]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.39525}
      />
      <mesh
        receiveShadow
        geometry={nodes.gd001.geometry}
        material={materials.gd}
        position={[7.63098, 5.47873, -2.5866]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.81893}
      />
      <mesh
        receiveShadow
        geometry={nodes.mouse001.geometry}
        material={materials.mouse}
        position={[6.81539, 3.08274, -2.58966]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.31463}
      />
      <mesh
        receiveShadow
        geometry={nodes.kiss001.geometry}
        material={materials.kiss}
        position={[6.9835, 5.19715, -2.583]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.77752}
      />
      <mesh
        receiveShadow
        geometry={nodes.slay.geometry}
        material={materials.slay}
        position={[3.15442, 5.62617, 1.10461]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.60662}
      />
      <mesh
        receiveShadow
        geometry={nodes.tp.geometry}
        material={materials.tp}
        position={[8.72845, 3.51681, -2.58299]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.33809}
      />
      <mesh
        receiveShadow
        geometry={nodes.no001.geometry}
        material={materials.no}
        position={[6.70659, 4.45644, -2.57859]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.63196}
      />
      <mesh
        receiveShadow
        geometry={nodes.bt001.geometry}
        material={materials.bt}
        position={[8.35606, 5.37967, -2.58848]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.75608}
      />
      <mesh
        receiveShadow
        geometry={nodes.bt002.geometry}
        material={materials.bt}
        position={[3.14814, 3.59476, -0.35588]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.41681}
      />
      <mesh
        receiveShadow
        geometry={nodes.sw.geometry}
        material={materials.sw}
        position={[8.68675, 4.96869, -2.55735]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.56253}
      />
      <mesh
        receiveShadow
        geometry={nodes.jp001.geometry}
        material={materials.jp}
        position={[6.75816, 3.67476, -2.58047]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.63818}
      />
      <mesh
        receiveShadow
        geometry={nodes.s1.geometry}
        material={materials.s1}
        position={[3.74313, 2.65401, 2.41457]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.10466}
      />
      <mesh
        receiveShadow
        geometry={nodes.s2.geometry}
        material={materials.s2}
        position={[3.91987, 2.57417, 1.66129]}
        rotation={[1.48203, -0.00031, 1.51534]}
        scale={0.10454}
      />
      <mesh
        receiveShadow
        geometry={nodes.s3.geometry}
        material={materials.s3}
        position={[3.45619, 2.648, 2.39472]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={0.1104}
      />
      <mesh
        receiveShadow
        geometry={nodes.s4.geometry}
        material={materials.s4}
        position={[3.91895, 2.50614, 2.31134]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.13482}
      />
      <mesh
        receiveShadow
        geometry={nodes.s7.geometry}
        material={materials.s7}
        position={[3.17916, 4.50462, 2.07062]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.27207}
      />
      <mesh
        receiveShadow
        geometry={nodes.s9.geometry}
        material={materials.s9}
        position={[3.14911, 4.15054, 0.12557]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.80899}
      />
      <mesh
        receiveShadow
        geometry={nodes.s8.geometry}
        material={materials.s8}
        position={[3.17991, 4.38767, 1.72459]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.25699}
      />
      <mesh
        receiveShadow
        geometry={nodes.s10.geometry}
        material={materials.s10}
        position={[3.18088, 4.00607, 1.02472]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.14083}
      />
      <mesh
        receiveShadow
        geometry={nodes.s13.geometry}
        material={materials.s13}
        position={[3.1796, 3.96145, 2.60736]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11202}
      />
      <mesh
        receiveShadow
        geometry={nodes.s14.geometry}
        material={materials.s14}
        position={[3.18304, 4.63827, 2.72725]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.13483}
      />
      <mesh
        receiveShadow
        geometry={nodes.s15.geometry}
        material={materials.s15}
        position={[3.14042, 5.38696, 1.88131]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.5941}
      />
      <mesh
        receiveShadow
        geometry={nodes.s16.geometry}
        material={materials.s16}
        position={[3.17911, 4.57002, 0.98988]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.28968}
      />
      <mesh
        receiveShadow
        geometry={nodes.s17.geometry}
        material={materials.s17}
        position={[3.16314, 4.60679, 0.66625]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.48259}
      />
      <mesh
        receiveShadow
        geometry={nodes.s18.geometry}
        material={materials.s18}
        position={[3.14406, 5.24717, 0.5666]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.42357}
      />
      <mesh
        receiveShadow
        geometry={nodes.s19.geometry}
        material={materials.s19}
        position={[3.13862, 4.99183, 1.08652]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.45273}
      />
      <mesh
        receiveShadow
        geometry={nodes.s20.geometry}
        material={materials.s20}
        position={[3.14857, 4.23033, 3.01202]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.34781}
      />
      <mesh
        receiveShadow
        geometry={nodes.s21.geometry}
        material={materials.s21}
        position={[3.16128, 3.42561, 2.95971]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.58138}
      />
      <mesh
        receiveShadow
        geometry={nodes.s22.geometry}
        material={materials.s22}
        position={[3.14304, 5.24925, 0.84078]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.12267}
      />
      <mesh
        receiveShadow
        geometry={nodes.s23.geometry}
        material={materials.s23}
        position={[3.14944, 3.55906, 1.24915]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.33012}
      />
      <mesh
        receiveShadow
        geometry={nodes.s24.geometry}
        material={materials.s24}
        position={[3.17863, 4.51617, 1.14522]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.08372}
      />
      <mesh
        receiveShadow
        geometry={nodes.s26.geometry}
        material={materials.s26}
        position={[3.13965, 5.39179, 2.41965]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.30773}
      />
      <mesh
        receiveShadow
        geometry={nodes.s26001.geometry}
        material={materials.s26}
        position={[3.17866, 4.24006, 2.6612]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.15031}
      />
      <mesh
        receiveShadow
        geometry={nodes.s27.geometry}
        material={materials.s27}
        position={[3.1831, 4.00249, 2.22522]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.19294}
      />
      <mesh
        receiveShadow
        geometry={nodes.s28.geometry}
        material={materials.s28}
        position={[3.13953, 5.25952, 1.35765]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.22269}
      />
      <mesh
        receiveShadow
        geometry={nodes.s28001.geometry}
        material={materials.s28}
        position={[3.14183, 3.61751, 0.32837]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.27425}
      />
      <mesh
        receiveShadow
        geometry={nodes.s30.geometry}
        material={materials.s30}
        position={[3.13978, 5.73891, 2.41783]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.31132}
      />
      <mesh
        receiveShadow
        geometry={nodes.S31.geometry}
        material={materials.S31}
        position={[3.14218, 4.18553, 0.6247]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.27009}
      />
      <mesh
        receiveShadow
        geometry={nodes.S32.geometry}
        material={materials.S32}
        position={[3.13906, 3.85927, 3.00479]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.32741}
      />
      <mesh
        receiveShadow
        geometry={nodes.S33.geometry}
        material={materials.S33}
        position={[3.13916, 4.91326, 1.49255]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.24357}
      />
      <mesh
        receiveShadow
        geometry={nodes.S34.geometry}
        material={materials.S34}
        position={[3.14941, 3.58065, 2.31905]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.34736}
      />
      <mesh
        receiveShadow
        geometry={nodes.S35.geometry}
        material={materials.S35}
        position={[3.13874, 4.56472, 3.01225]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.21543}
      />
      <mesh
        receiveShadow
        geometry={nodes.S36001.geometry}
        material={materials.S36}
        position={[3.18012, 4.58735, 1.87074]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.16017}
      />
      <mesh
        receiveShadow
        geometry={nodes.S37.geometry}
        material={materials.S37}
        position={[3.18124, 4.50329, 1.36274]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.36542}
      />
      <mesh
        receiveShadow
        geometry={nodes.S38.geometry}
        material={materials.S38}
        position={[3.14615, 5.24697, 2.90909]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.29582}
      />
      <mesh
        receiveShadow
        geometry={nodes.S39.geometry}
        material={materials.S39}
        position={[3.14927, 4.98515, 2.50933]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.40141}
      />
      <mesh
        receiveShadow
        geometry={nodes.S40.geometry}
        material={materials.S40}
        position={[3.17801, 4.15785, 1.26631]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.40193}
      />
      <mesh
        receiveShadow
        geometry={nodes.S41.geometry}
        material={materials.S41}
        position={[3.14176, 4.91469, 1.91093]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.2222}
      />
      <mesh
        receiveShadow
        geometry={nodes.s42.geometry}
        material={materials.s42}
        position={[3.17801, 4.31105, 2.00196]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.1158}
      />
      <mesh
        receiveShadow
        geometry={nodes.s43.geometry}
        material={materials.s43}
        position={[3.71404, 3.1207, 2.42617]}
        rotation={[1.63657, 0.01444, 2.90575]}
        scale={[0.09466, 0.06711, 0.09466]}
      />
      <mesh
        receiveShadow
        geometry={nodes.s44.geometry}
        material={materials.s44}
        position={[3.14222, 3.30005, 0.37465]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11412}
      />
      <mesh
        receiveShadow
        geometry={nodes.s45.geometry}
        material={materials.s45}
        position={[3.78113, 2.6471, 1.69371]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={0.15217}
      />
      <mesh
        receiveShadow
        geometry={nodes.s46.geometry}
        material={materials.s46}
        position={[4.2457, 3.3832, 2.26719]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.10042}
      />
      <mesh
        receiveShadow
        geometry={nodes.s47.geometry}
        material={materials.s47}
        position={[3.91835, 2.57674, 2.44144]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.1073}
      />
      <mesh
        receiveShadow
        geometry={nodes.s48.geometry}
        material={materials.s48}
        position={[3.1384, 3.61918, 2.52934]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.09566}
      />
      <mesh
        receiveShadow
        geometry={nodes.s49.geometry}
        material={materials.s49}
        position={[3.15488, 3.24067, 0.93737]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.13627}
      />
      <mesh
        receiveShadow
        geometry={nodes.s50.geometry}
        material={materials.s50}
        position={[4.12333, 2.91566, 2.41184]}
        rotation={[1.57282, 0.04247, 2.64104]}
        scale={0.14448}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6328001.geometry}
        material={materials.IMG_6328}
        position={[3.17811, 4.21493, 2.24099]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.19719}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6322001.geometry}
        material={materials.IMG_6322}
        position={[3.18206, 4.24782, 2.11802]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.25676}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6317001.geometry}
        material={materials.IMG_6317}
        position={[3.18765, 4.05477, 1.76667]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.30766}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6318001.geometry}
        material={materials.IMG_6318}
        position={[3.19312, 4.31025, 2.44024]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.26188}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6319001.geometry}
        material={materials.IMG_6319}
        position={[3.17802, 3.94616, 1.91375]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.19242}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6320001.geometry}
        material={materials.IMG_6320}
        position={[3.18027, 4.19217, 1.48136]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.24075}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6321001.geometry}
        material={materials.IMG_6321}
        position={[3.18241, 4.24949, 1.04024]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.33666}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6323001.geometry}
        material={materials.IMG_6323}
        position={[3.14317, 3.87023, 0.71778]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.28662}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6324001.geometry}
        material={materials.IMG_6324}
        position={[3.18572, 4.362, 1.87046]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.27375}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6325001.geometry}
        material={materials.IMG_6325}
        position={[3.18167, 4.41594, 2.32417]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.14606}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6326001.geometry}
        material={materials.IMG_6326}
        position={[3.1798, 4.12352, 1.96144]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.16073}
      />
      <mesh
        receiveShadow
        geometry={nodes.IMG_6327001.geometry}
        material={materials.IMG_6327}
        position={[3.18087, 4.08748, 2.44743]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.13403}
      />
      <mesh
        receiveShadow
        geometry={nodes.shh1.geometry}
        material={materials.shh1}
        position={[3.14818, 3.97815, -0.3127]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.37906}
      />
      <mesh
        receiveShadow
        geometry={nodes.shh1001.geometry}
        material={materials.shh1}
        position={[3.17132, 4.9667, 2.98681]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.31309}
      />
      <mesh
        receiveShadow
        geometry={nodes.shh2.geometry}
        material={materials.shh2}
        position={[3.21975, 3.33949, -0.08128]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.41048}
      />
      <mesh
        receiveShadow
        geometry={nodes.shh3.geometry}
        material={materials.shh3}
        position={[7.71108, 3.65457, -2.58681]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={1.9586}
      />
      <mesh
        receiveShadow
        geometry={nodes.shhroompic.geometry}
        material={materials.shhroompic}
        position={[3.16328, 3.53543, 1.91796]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.4001}
      />
      <mesh
        receiveShadow
        geometry={nodes.kentaylor_gremlins700.geometry}
        material={materials.kentaylor_gremlins700}
        position={[8.68322, 4.20786, -2.58838]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.69356}
      />
      <mesh
        receiveShadow
        geometry={nodes['poster-47'].geometry}
        material={materials['poster-47']}
        position={[3.1392, 3.62628, -0.92121]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <group
        position={[3.13927, 3.63483, 0.73964]}
        rotation={[Math.PI / 2, -0.0304, -Math.PI / 2]}
        scale={0.14963}
      >
        <mesh
          receiveShadow
          geometry={nodes.Plane104.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_2.geometry}
          material={materials.PaletteMaterial003}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_3.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_4.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_5.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_6.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_7.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_8.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_9.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          receiveShadow
          geometry={nodes.Plane104_10.geometry}
          material={materials.PaletteMaterial004}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/wall_art-transformed.glb');
