/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 wall_art_tier_2.glb -o src/WallArtTierTwo.jsx -p 5 -r . -TjDsS 
Files: wall_art_tier_2.glb [15.32MB] > wall_art_tier_2-transformed.glb [1.83MB] (88%)
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useDetectGPU } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/wall_art_tier_2-transformed.glb');
  const gpu = useDetectGPU()
  return (
    <>
    {gpu.tier >= 2 && 
      <group {...props} dispose={null}>
      <mesh
      receiveShadow
      geometry={nodes.car002.geometry}
      material={materials.car}
      position={[8.68258, 3.10231, -2.58347]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.31879}
      />
      <mesh
      receiveShadow
      geometry={nodes.mouse001.geometry}
      material={materials.mouse}
      position={[6.81539, 3.08274, -2.58966]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.31463}
      />
      <mesh
      receiveShadow
      geometry={nodes.slay.geometry}
      material={materials.slay}
      position={[3.15442, 5.62617, 1.10461]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.60662}
      />
      <mesh
      receiveShadow
      geometry={nodes.sw.geometry}
      material={materials.sw}
      position={[8.68675, 4.96869, -2.55735]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.56253}
      />
      <mesh
      receiveShadow
      geometry={nodes.jp001.geometry}
      material={materials.jp}
      position={[6.75816, 3.67476, -2.58047]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.63818}
      />
      <mesh
      receiveShadow
      geometry={nodes.s7.geometry}
      material={materials.s7}
      position={[3.17916, 4.50462, 2.07062]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.27207}
      />
      <mesh
      receiveShadow
      geometry={nodes.s8.geometry}
      material={materials.s8}
      position={[3.17991, 4.38767, 1.72459]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.25699}
      />
      <mesh
      receiveShadow
      geometry={nodes.s10.geometry}
        material={materials.s10}
        position={[3.18088, 4.00607, 1.02472]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.14083}
        />
        <mesh
        receiveShadow
        geometry={nodes.s13.geometry}
        material={materials.s13}
        position={[3.1796, 3.96145, 2.60736]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11202}
        />
        <mesh
        receiveShadow
        geometry={nodes.s14.geometry}
        material={materials.s14}
        position={[3.18304, 4.63827, 2.72725]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.13483}
        />
        <mesh
        receiveShadow
        geometry={nodes.s15.geometry}
        material={materials.s15}
        position={[3.14042, 5.38696, 1.88131]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.5941}
        />
        <mesh
        receiveShadow
        geometry={nodes.s16.geometry}
        material={materials.s16}
        position={[3.17911, 4.57002, 0.98988]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.28968}
        />
        <mesh
        receiveShadow
        geometry={nodes.s17.geometry}
        material={materials.s17}
        position={[3.16314, 4.60679, 0.66625]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.48259}
        />
        <mesh
        receiveShadow
        geometry={nodes.s18.geometry}
        material={materials.s18}
        position={[3.14406, 5.24717, 0.5666]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.42357}
        />
        <mesh
        receiveShadow
        geometry={nodes.s19.geometry}
        material={materials.s19}
        position={[3.13862, 4.99183, 1.08652]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.45273}
        />
        <mesh
        receiveShadow
        geometry={nodes.s20.geometry}
        material={materials.s20}
        position={[3.14857, 4.23033, 3.01202]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.34781}
        />
        <mesh
        receiveShadow
        geometry={nodes.s21.geometry}
        material={materials.s21}
        position={[3.16128, 3.42561, 2.95971]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.58138}
        />
        <mesh
        receiveShadow
        geometry={nodes.s23.geometry}
        material={materials.s23}
        position={[3.14944, 3.55906, 1.24915]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.33012}
        />
        <mesh
        receiveShadow
        geometry={nodes.s24.geometry}
        material={materials.s24}
        position={[3.17863, 4.51617, 1.14522]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.08372}
        />
        <mesh
        receiveShadow
        geometry={nodes.s26.geometry}
        material={materials.s26}
        position={[3.13965, 5.39179, 2.41965]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.30773}
        />
        <mesh
        receiveShadow
        geometry={nodes.s26001.geometry}
        material={materials.s26}
        position={[3.17866, 4.24006, 2.6612]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.15031}
        />
        <mesh
        receiveShadow
        geometry={nodes.s27.geometry}
        material={materials.s27}
        position={[3.1831, 4.00249, 2.22522]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.19294}
        />
        <mesh
        receiveShadow
        geometry={nodes.s30.geometry}
        material={materials.s30}
        position={[3.13978, 5.73891, 2.41783]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.31132}
        />
        <mesh
        receiveShadow
        geometry={nodes.S32.geometry}
        material={materials.S32}
        position={[3.13906, 3.85927, 3.00479]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.32741}
        />
        <mesh
        receiveShadow
        geometry={nodes.S34.geometry}
        material={materials.S34}
        position={[3.14941, 3.58065, 2.31905]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.34736}
        />
        <mesh
        receiveShadow
        geometry={nodes.S36001.geometry}
        material={materials.S36}
        position={[3.18012, 4.58735, 1.87074]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.16017}
        />
        <mesh
        receiveShadow
        geometry={nodes.S37.geometry}
        material={materials.S37}
        position={[3.18124, 4.50329, 1.36274]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.36542}
        />
        <mesh
        receiveShadow
        geometry={nodes.S40.geometry}
      material={materials.S40}
      position={[3.17801, 4.15785, 1.26631]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.40193}
      />
      <mesh
      receiveShadow
      geometry={nodes.s49.geometry}
      material={materials.s49}
      position={[3.15488, 3.24067, 0.93737]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.13627}
      />
      <mesh
      receiveShadow
      geometry={nodes.shhroompic.geometry}
      material={materials.shhroompic}
      position={[3.16328, 3.53543, 1.91796]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={0.4001}
      />
      <mesh
      receiveShadow
      geometry={nodes['poster-47'].geometry}
      material={materials['poster-47']}
      position={[3.1392, 3.62628, -0.92121]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      </group>
    }
    </>
    );
  }
  
  useGLTF.preload('/wall_art_tier_2-transformed.glb');
  