/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 render_clock.glb -o src/Model_Clock.jsx -p 5 -r . -TjDsS 
Files: render_clock.glb [23.02KB] > render_clock-transformed.glb [11.46KB] (50%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelClock(props) {
  const { nodes, materials } = useGLTF('/render_clock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[8.73703, 2.08456, -2.16681]} rotation={[Math.PI, -1.38555, -Math.PI / 2]} scale={[-0.00385, -0.00927, -0.0144]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane063.geometry} material={materials['Material.020']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_1.geometry} material={materials.clock} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_2.geometry} material={materials['Material.008']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_3.geometry} material={materials['clocknums fin']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_4.geometry} material={materials['Material.020']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_5.geometry} material={materials['clocknums fin.005']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane063_6.geometry} material={materials['clocknums fin.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/render_clock-transformed.glb')
