/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 room_2.glb -o src/RoomTwo.jsx -p 5 -r . -TjDsS 
Files: room_2.glb [349.18MB] > room_2-transformed.glb [12.18MB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/room_2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials.denmin_fabric_02} position={[8.48249, 1.90192, -2.15016]} rotation={[-1.71468, -0.98677, -1.15414]} scale={0.29401} />
      <mesh castShadow receiveShadow geometry={nodes.Plane003.geometry} material={materials['Flannel Yarn Dyed Plaid Fabric Red']} position={[8.46764, 1.82383, -1.83129]} scale={[0.27147, 0.39217, 0.38279]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane004.geometry} material={materials.fabric_pattern_07} position={[8.47839, 1.92612, -1.94537]} rotation={[-1.26548, 0.88326, 1.03371]} scale={0.2099} />
      <mesh castShadow receiveShadow geometry={nodes.chairLeatherTop.geometry} material={materials.fabric_leather_02} position={[5.89594, 2.56784, 2.10543]} rotation={[0, 1.07514, 0]} scale={0.68262} />
      <group position={[5.89286, 1.04272, 1.6781]} rotation={[-1.22332, -0.00711, -2.85383]} scale={[-0.0199, -0.02047, -0.02523]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder011.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder011_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.bedside_body.geometry} material={materials.Wood} position={[8.36467, 1.55197, -2.30015]} rotation={[-Math.PI, 1.5274, -Math.PI]} scale={[0.26348, 0.40816, 0.4185]} />
      <mesh castShadow receiveShadow geometry={nodes.bedisdeL3.geometry} material={materials.Wood} position={[8.71589, 0.88006, -2.49494]} rotation={[-2.40743, 1.53593, 2.42855]} scale={[0.18318, 0.28376, 0.29094]} />
      <mesh castShadow receiveShadow geometry={nodes.bedsideL1.geometry} material={materials.Wood} position={[8.73389, 0.8845, -2.14167]} rotation={[-2.40743, 1.53593, 2.42855]} scale={[0.18318, 0.28376, 0.29094]} />
      <mesh castShadow receiveShadow geometry={nodes.bedsideL2.geometry} material={materials.Wood} position={[8.02625, 0.8845, -2.11094]} rotation={[-2.40743, 1.53593, 2.42855]} scale={[0.18318, 0.28376, 0.29094]} />
      <mesh castShadow receiveShadow geometry={nodes.bedsideL4.geometry} material={materials.Wood} position={[8.00825, 0.88006, -2.4642]} rotation={[-2.40743, 1.53593, 2.42855]} scale={[0.18318, 0.28376, 0.29094]} />
      <mesh castShadow receiveShadow geometry={nodes.bedsideUpperDrawer.geometry} material={materials['Dark oak fine wood texture']} position={[8.35211, 1.79047, -2.02549]} rotation={[-Math.PI, 1.5274, -Math.PI]} scale={[0.26348, 0.40816, 0.43626]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube047.geometry} material={materials.Wood} position={[8.38147, 1.42412, -2.03714]} rotation={[-Math.PI, 1.52739, -Math.PI]} scale={[0.27387, 0.2299, 0.38256]} />
      <group position={[8.41348, 1.41693, -1.72333]} rotation={[-Math.PI, 1.5274, -Math.PI]} scale={0.02721}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere004.geometry} material={materials.PaletteMaterial003} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere004_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={materials['Magnificent wood']} position={[8.38147, 1.42412, -2.03714]} rotation={[-Math.PI, 1.52739, -Math.PI]} scale={[0.27387, 0.2299, 0.38256]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube010.geometry} material={materials['Magnificent wood']} position={[8.35211, 1.79047, -2.02549]} rotation={[-Math.PI, 1.5274, -Math.PI]} scale={[0.26348, 0.40816, 0.43626]} />
      <mesh castShadow receiveShadow geometry={nodes.Mushroom_Lamp.geometry} material={materials.MI_DirtyPlastic13} position={[8.11863, 2.15597, -2.34916]} scale={0.73403} />
      <mesh castShadow receiveShadow geometry={nodes.Barbel_3Kg.geometry} material={materials.Fabric} position={[8.46874, 0.95661, -0.89506]} scale={1.35331} />
      <mesh castShadow receiveShadow geometry={nodes.Barbel_3Kg001.geometry} material={materials.Fabric} position={[8.56466, 0.97828, -1.11225]} rotation={[0, -0.84164, 0]} scale={1.35331} />
      <group position={[8.39408, 0.97776, 0.10381]} scale={1.78452}>
        <mesh castShadow receiveShadow geometry={nodes.mesh003.geometry} material={materials['mustang-damen-schuhe-sneakers-Sole']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_1.geometry} material={materials['Innen sole']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_2.geometry} material={materials.PaletteMaterial005} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_3.geometry} material={materials.PaletteMaterial006} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_4.geometry} material={materials['leather 01.005']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_5.geometry} material={materials.Innenfuter} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_6.geometry} material={materials['leather 01.005']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_7.geometry} material={materials['leather 01.004']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_8.geometry} material={materials['leather 01.005']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_9.geometry} material={materials.Innenfuter} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_10.geometry} material={materials['Material.029']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_11.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_12.geometry} material={materials.Garn} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_13.geometry} material={materials.Lasche} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_14.geometry} material={materials['leather 01.008']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_15.geometry} material={materials['schnürsenkel.004']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh003_16.geometry} material={materials.PaletteMaterial007} />
      </group>
      <group position={[8.20237, 0.98439, -0.0448]} scale={1.78452}>
        <mesh castShadow receiveShadow geometry={nodes.mesh002.geometry} material={materials['mustang-damen-schuhe-sneakers-Sole.R']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_1.geometry} material={materials['Innen sole']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_2.geometry} material={materials.PaletteMaterial005} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_3.geometry} material={materials.PaletteMaterial006} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_4.geometry} material={materials['Innen sole.R']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_5.geometry} material={materials['leather 01.005']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_6.geometry} material={materials.Innenfuter} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_7.geometry} material={materials['leather 01.005']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_8.geometry} material={materials['leather 01.004']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_9.geometry} material={materials['leather 01.005']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_10.geometry} material={materials.Innenfuter} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_11.geometry} material={materials['Material.023']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_12.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_13.geometry} material={materials.Garn} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_14.geometry} material={materials.Lasche} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_15.geometry} material={materials['leather 01.008']} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_16.geometry} material={materials.PaletteMaterial007} />
        <mesh castShadow receiveShadow geometry={nodes.mesh002_17.geometry} material={materials['schnürsenkel.004']} />
      </group>
      <group position={[8.00662, 1.2407, -1.44285]} rotation={[Math.PI, -0.99781, Math.PI]} scale={1.55689}>
        <mesh castShadow receiveShadow geometry={nodes.Cube167.geometry} material={materials['bag_gray main']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_1.geometry} material={materials['bag_dark gray']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_2.geometry} material={materials['bag_metal 1']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_3.geometry} material={materials.bag_leather} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_4.geometry} material={materials['bag_metal 2']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_5.geometry} material={materials.bag_plate} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_6.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_7.geometry} material={materials['bag_dark gray']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_8.geometry} material={materials.bag_zipper} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_9.geometry} material={materials['bag_metal 1']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube167_10.geometry} material={materials['bag_metal 1']} />
      </group>
      <group position={[8.01947, 2.0281, -2.10942]} rotation={[0.0761, -0.14554, 0.01106]} scale={1.32359}>
        <mesh castShadow receiveShadow geometry={nodes.comb11.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.comb11_1.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.comb11_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group position={[8.15868, 2.04951, -2.34039]} rotation={[-3.05675, 1.50357, 3.01958]} scale={1.96894}>
        <mesh castShadow receiveShadow geometry={nodes.Cube173.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Cube173_1.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Cube173_2.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Cube173_3.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.SM_MushroomLamp01001.geometry} material={materials.MI_DirtyPlastic12} position={[8.11863, 2.15597, -2.34916]} scale={0.73403} />
      <mesh castShadow receiveShadow geometry={nodes.SM_MushroomLamp01002.geometry} material={materials.PaletteMaterial004} position={[8.11863, 2.15597, -2.34916]} scale={0.73403} />
    </group>
  )
}

useGLTF.preload('/room_2-transformed.glb')
