/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 room_3.glb -o src/RoomThree.jsx -p 5 -r . -TjDsS 
Files: room_3.glb [132.29MB] > room_3-transformed.glb [3.91MB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/room_3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube029.geometry} material={materials['Magnificent wood']} position={[3.8675, 2.36059, 1.31098]} rotation={[Math.PI, -0.00212, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube030.geometry} material={materials['Magnificent wood']} position={[4.4119, 1.57665, 2.76811]} rotation={[Math.PI, -0.00212, Math.PI]} scale={[0.05329, 0.74066, 0.07404]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube032.geometry} material={materials['Magnificent wood']} position={[4.40926, 1.57665, -0.15694]} rotation={[Math.PI, -0.00212, Math.PI]} scale={[0.05329, 0.74066, 0.07404]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube031.geometry} material={materials['Magnificent wood']} position={[3.31436, 1.57665, 2.7708]} rotation={[Math.PI, -0.00212, Math.PI]} scale={[0.05329, 0.74066, 0.07404]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube033.geometry} material={materials['Magnificent wood']} position={[3.31172, 1.57665, -0.15424]} rotation={[Math.PI, -0.00212, Math.PI]} scale={[0.05329, 0.74066, 0.07404]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube034.geometry} material={materials['Magnificent wood']} position={[3.86641, 2.00654, 1.30195]} rotation={[Math.PI, -0.00212, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube036.geometry} material={materials['Magnificent wood']} position={[4.13078, 1.88732, 0.44723]} rotation={[Math.PI, -0.00212, Math.PI]} scale={[0.33112, 0.15161, 0.49687]} />
      <mesh castShadow receiveShadow geometry={nodes.deskHandleU.geometry} material={materials.PaletteMaterial001} position={[4.50754, 2.15494, 0.44054]} rotation={[Math.PI, -0.00212, Math.PI]} scale={[0.03542, 0.03243, 0.04108]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.PaletteMaterial002} position={[4.47627, 2.15311, 0.44218]} rotation={[-Math.PI, -0.00212, -1.60063]} scale={[0.01284, 0.04716, 0.01618]} />
      <mesh castShadow receiveShadow geometry={nodes.deskHandleD.geometry} material={materials.PaletteMaterial001} position={[4.50778, 1.88966, 0.45619]} rotation={[Math.PI, -0.00212, Math.PI]} scale={[0.03542, 0.03243, 0.04108]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials.PaletteMaterial002} position={[4.44931, 1.88782, 0.45789]} rotation={[-Math.PI, -0.00212, -1.60063]} scale={[0.01284, 0.04716, 0.01618]} />
      <mesh castShadow receiveShadow geometry={nodes.compHead.geometry} material={materials.PaletteMaterial002} position={[3.55351, 3.20897, 2.14689]} rotation={[0, 0.60667, 0]} scale={[0.36907, 0.41434, 0.5585]} />
      <group position={[3.57264, 1.75082, -1.16755]} rotation={[-3.02039, -0.15262, -1.70998]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane001_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane001_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane001_3.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube020.geometry} material={materials['Old white plastic']} position={[4.25849, 2.43437, 1.26738]} rotation={[-Math.PI, 1.03639, -Math.PI]} scale={[0.08302, 0.02509, 0.10661]} />
      <group position={[3.50792, 2.60453, 1.00324]} rotation={[-3.13913, -0.48119, 0.00228]} scale={[0.08025, 0.16613, 0.16897]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane027.geometry} material={materials['notebook page']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane027_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.pencilHolder.geometry} material={materials.PaletteMaterial002} position={[3.55216, 2.4149, 0.37942]} scale={[0.10099, 0.13355, 0.1046]} />
      <group position={[3.59058, 2.59723, 0.40777]} rotation={[0.58743, 0.24553, 0.00029]} scale={[0.01057, 0.18126, 0.00912]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013_4.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder013_5.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.58119, 2.58372, 0.37647]} rotation={[-0.6564, -0.25353, -0.34408]} scale={[0.01057, 0.18067, 0.00915]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_4.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder014_5.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.59058, 2.61444, 0.40777]} rotation={[0.41403, 0.10551, 0.00476]} scale={[0.01057, 0.18086, 0.00914]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_4.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder015_5.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.53106, 3.04255, 0.00858]} rotation={[0, 0.66379, 0]} scale={0.05772}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder021.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder021_1.geometry} material={materials.PaletteMaterial004} />
      </group>
      <group position={[3.55767, 2.63404, 0.8626]} rotation={[-3.13928, -0.3308, 0.00189]} scale={[0.08025, 0.16613, 0.16897]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane041.geometry} material={materials['notebook page']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane041_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={materials['Magnificent wood']} position={[4.1292, 2.15817, 0.45037]} rotation={[Math.PI, -0.00212, Math.PI]} />
      <group position={[4.34849, 2.42477, 2.02359]} rotation={[-3.13739, -0.11547, -3.07637]} scale={[0.22893, 0.29114, 0.54064]}>
        <mesh castShadow receiveShadow geometry={nodes.Plane111.geometry} material={materials['Old white plastic']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane111_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane111_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane111_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane111_4.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Ball.geometry} material={materials.GolfBall} position={[4.0585, 2.44678, 2.6679]} rotation={[0, -0.41812, 0]} scale={1.73239} />
      <mesh castShadow receiveShadow geometry={nodes['Old_Book_Julius_Caesar_-_Shakespeare'].geometry} material={materials['Julius Caesar - Shakespeare']} position={[3.75239, 2.4248, 0.00975]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.86411} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_plastic.geometry} material={materials.PaletteMaterial005} position={[3.72476, 2.64987, 1.11974]} rotation={[Math.PI, -0.80144, Math.PI]} scale={3.17474} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_plastic001.geometry} material={materials.PaletteMaterial005} position={[3.60538, 2.61993, 1.24513]} rotation={[0, -0.27212, 0]} scale={3.17474} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_plastic002.geometry} material={materials.PaletteMaterial005} position={[3.63965, 2.65426, 1.10079]} rotation={[Math.PI, -0.80144, Math.PI]} scale={3.17474} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_plastic003.geometry} material={materials.PaletteMaterial005} position={[4.03443, 2.41305, 0.75398]} rotation={[0, -0.27212, 0]} scale={3.17474} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_plastic004.geometry} material={materials.PaletteMaterial005} position={[4.02602, 2.411, 0.72695]} rotation={[0, -0.75643, 0]} scale={3.17474} />
      <mesh castShadow receiveShadow geometry={nodes['Corner_table-02'].geometry} material={materials['Magnificent wood']} position={[3.71639, 0.8998, -1.87044]} scale={1.97538} />
      <group position={[4.04818, 2.44681, 0.0184]} rotation={[Math.PI, -0.5292, Math.PI]} scale={-1.72073}>
        <mesh castShadow receiveShadow geometry={nodes.Circle051.geometry} material={materials.PaletteMaterial006} />
        <mesh castShadow receiveShadow geometry={nodes.Circle051_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.62783, 2.45315, 1.10553]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={1.57067}>
        <mesh castShadow receiveShadow geometry={nodes.Cube186.geometry} material={materials['Burlington Leather']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube186_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube186_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube186_3.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.6101, 2.54432, 1.15221]} rotation={[-Math.PI, 1.41977, Math.PI / 2]} scale={1.57067}>
        <mesh castShadow receiveShadow geometry={nodes.Cube027.geometry} material={materials['Burlington Leather']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube027_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube027_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube027_3.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.81175, 2.43534, 0.00486]} rotation={[0.03023, -0.30773, 0.03963]} scale={3.36323}>
        <mesh castShadow receiveShadow geometry={nodes.Plane007.geometry} material={materials.PaletteMaterial007} />
        <mesh castShadow receiveShadow geometry={nodes.Plane007_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane007_2.geometry} material={materials.PaletteMaterial008} />
        <mesh castShadow receiveShadow geometry={nodes.Plane007_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Plane007_4.geometry} material={materials.PaletteMaterial009} />
        <mesh castShadow receiveShadow geometry={nodes.Plane007_5.geometry} material={materials.Body_2} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes['Object_08_-_Default_0002'].geometry} material={materials['Old white plastic']} position={[4.25852, 2.42165, 1.17342]} rotation={[-1.62409, 0.01567, 2.50065]} scale={0.0112} />
      <mesh castShadow receiveShadow geometry={nodes['Object_08_-_Default_0003'].geometry} material={materials['Old white plastic']} position={[3.70308, 2.44177, 1.79878]} rotation={[-1.75293, 0.30589, -2.48948]} scale={0.0112} />
      <mesh castShadow receiveShadow geometry={nodes['et_09_-_Default_0'].geometry} material={materials.PaletteMaterial002} position={[3.57872, 2.64754, 2.00447]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.01402} />
      <mesh castShadow receiveShadow geometry={nodes['et_09_-_Default_0001'].geometry} material={materials.PaletteMaterial002} position={[3.61117, 2.63709, 1.97267]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.01792} />
      <mesh castShadow receiveShadow geometry={nodes.old_brick_01.geometry} material={materials['old brick 01']} position={[3.94816, 2.41821, 0.19684]} rotation={[0, -0.21626, 0]} scale={0.12317} />
      <mesh castShadow receiveShadow geometry={nodes.peach_core.geometry} material={materials['Material.peach.core']} position={[4.19465, 2.43187, 0.25977]} rotation={[-0.70354, 0.02375, -1.56281]} scale={1.76926} />
      <mesh castShadow receiveShadow geometry={nodes['Magnifier-Freepolyorg001'].geometry} material={materials['default']} position={[3.69662, 2.64861, 1.09]} rotation={[0, -0.76179, 0]} scale={0.85656} />
      <group position={[3.67117, 2.46384, -1.95239]} rotation={[1.83052, 0.61123, -2.38185]} scale={1.29916}>
        <mesh castShadow receiveShadow geometry={nodes.Plane081.geometry} material={materials['Material.037']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane081_1.geometry} material={materials['Material.038']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane081_2.geometry} material={materials['Material.039']} />
        <mesh castShadow receiveShadow geometry={nodes.Plane081_3.geometry} material={materials['Circle_BAKED.001']} />
      </group>
      <group position={[3.68874, 2.45666, 1.3846]} rotation={[-Math.PI / 2, 0, 1.76038]} scale={1.70216}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder112.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder112_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder112_2.geometry} material={materials.PaletteMaterial010} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder112_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder112_4.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder112_5.geometry} material={materials.PaletteMaterial011} />
      </group>
      <group position={[3.97311, 2.43567, 1.41015]} rotation={[-2.75797, 1.14128, 2.70906]} scale={2.55779}>
        <mesh castShadow receiveShadow geometry={nodes.Data_Widowmaker_Eyes_Iris002.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Data_Widowmaker_Eyes_Iris002_1.geometry} material={materials.PaletteMaterial008} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Drinking_Glass_Model003.geometry} material={materials.PaletteMaterial012} position={[4.21799, 2.40663, 0.56561]} scale={1.81398} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body.geometry} material={materials.PaletteMaterial002} position={[3.77045, 2.41602, 0.2023]} rotation={[0, 0, 0.45167]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body001.geometry} material={materials.PaletteMaterial002} position={[3.55067, 2.42356, 0.37151]} rotation={[Math.PI, -0.77363, -2.68992]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body002.geometry} material={materials.PaletteMaterial002} position={[3.60973, 2.42167, 0.42137]} rotation={[Math.PI, 1.36143, -2.68992]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body_frame.geometry} material={materials.PaletteMaterial002} position={[3.77011, 2.41484, 0.2023]} rotation={[0, 0, 0.45167]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body_frame001.geometry} material={materials.PaletteMaterial002} position={[3.76931, 2.4165, 0.2023]} rotation={[0, 0, 0.45167]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body_frame002.geometry} material={materials.PaletteMaterial002} position={[3.55149, 2.42404, 0.37071]} rotation={[Math.PI, -0.77363, -2.68992]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body_frame003.geometry} material={materials.PaletteMaterial002} position={[3.55091, 2.42238, 0.37127]} rotation={[Math.PI, -0.77363, -2.68992]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body_frame004.geometry} material={materials.PaletteMaterial002} position={[3.60997, 2.42214, 0.42249]} rotation={[Math.PI, 1.36143, -2.68992]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body_frame006.geometry} material={materials.PaletteMaterial002} position={[3.97553, 2.41297, 0.3441]} rotation={[0, -1.13182, 0.45167]} scale={1.63684} />
      <mesh castShadow receiveShadow geometry={nodes.Paper_clip_body_frame007.geometry} material={materials.PaletteMaterial002} position={[3.97587, 2.41131, 0.34483]} rotation={[0, -1.13182, 0.45167]} scale={1.63684} />
      <group position={[4.04818, 2.44681, 0.0184]} rotation={[0, 0.5292, -Math.PI]} scale={[-1.72073, 1.72073, 1.72073]}>
        <mesh castShadow receiveShadow geometry={nodes.Circle052.geometry} material={materials.PaletteMaterial006} />
        <mesh castShadow receiveShadow geometry={nodes.Circle052_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/room_3-transformed.glb')
