/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 room_1.glb -o src/RoomOne.jsx -p 5 -r . -TjDsS 
Files: room_1.glb [211.14MB] > room_1-transformed.glb [9.89MB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/room_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials['Quilted velvet coverlet black']} position={[6.54339, 0.95337, 1.36371]} scale={[2.27722, 1, 1.67521]} />
      <mesh castShadow receiveShadow geometry={nodes.bedframe.geometry} material={materials.Wood} position={[6.69323, 1.56144, -0.74012]} rotation={[0, -0.01029, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[6.7053, 1.82504, -0.74779]} rotation={[0, -1.55913, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.blanket.geometry} material={materials['Patchwork blanket for kids']} position={[6.67601, 2.64527, -0.49158]} rotation={[Math.PI, -1.54969, Math.PI]} scale={[1.08546, 1, 1.06053]} />
      <mesh castShadow receiveShadow geometry={nodes.pillow.geometry} material={materials['Lemon Patterned Flannel Fabric']} position={[6.24359, 2.26081, -2.16214]} rotation={[1.36138, 1.54682, -0.30257]} scale={[0.40586, 0.50992, 0.5265]} />
      <mesh castShadow receiveShadow geometry={nodes.pillow001.geometry} material={materials['Lemon Patterned Flannel Fabric']} position={[7.20789, 2.26615, -2.13458]} rotation={[2.03889, 1.4524, -0.93697]} scale={[0.40586, 0.50992, 0.50992]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Magnificent wood']} position={[5.06108, 4.13997, -2.7071]} rotation={[-Math.PI, 0.00161, 0]} scale={[-1.16779, -1.71969, -0.16649]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={materials['Basalt tiles.001']} position={[5.00147, 3.76926, -1.55381]} scale={[3.05, 2.855, 3.05]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={materials['Worn Old Wood Planks']} position={[5.88322, 3.52281, 0.15419]} scale={[3.05, 2.855, 3.05]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={materials['Panels 02']} position={[5.00147, 3.76926, -1.55381]} scale={[3.05, 2.855, 3.05]} />
      <mesh castShadow receiveShadow geometry={nodes.CURTAIN_01001.geometry} material={materials['olive fabric']} position={[4.15322, 3.85594, -2.38999]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.81528, -1.43726, -2.05712]} />
      <mesh castShadow receiveShadow geometry={nodes.CURTAIN_02001.geometry} material={materials['olive fabric']} position={[6.23756, 3.86585, -2.39566]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.85695, 1.43726, 2.05712]} />
      <mesh castShadow receiveShadow geometry={nodes.hook.geometry} material={materials['Matt paint black.001']} position={[5.15512, 6.07979, -2.42162]} rotation={[Math.PI, 0, Math.PI / 2]} scale={1.43726} />
      <mesh castShadow receiveShadow geometry={nodes.metal_rod.geometry} material={materials.Wood} position={[5.15512, 6.07981, -2.39539]} rotation={[Math.PI, 0, Math.PI]} scale={1.43726} />
    </group>
  )
}

useGLTF.preload('/room_1-transformed.glb')
