/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 room_4.glb -o src/RoomFour.jsx -p 5 -r . -TjDsS 
Files: room_4.glb [168.72MB] > room_4-transformed.glb [4.13MB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/room_4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.lowerBookshelf.geometry} material={materials['Magnificent wood']} position={[3.39494, 4.18006, -1.25683]} scale={[0.302, 1, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.upperBookshelf.geometry} material={materials['Magnificent wood']} position={[3.35284, 4.76898, -0.88191]} scale={[0.302, 1, 1.36665]} />
      <mesh castShadow receiveShadow geometry={nodes.corkboard.geometry} material={materials['Cork natural']} position={[3.0905, 4.29743, 1.83965]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.45512, 1.17691, 0.96003]} />
      <group position={[3.23174, 4.03593, 1.64712]} rotation={[0, 0, -Math.PI / 2]} scale={0.01653}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere001_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.18963, 4.29856, 1.47946]} rotation={[0.13278, 0.18097, -1.12154]} scale={0.00917}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere001_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.20559, 4.52949, 2.10692]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.01019}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere006.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere006_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.58801, 4.33759, -1.42534]} scale={[0.06532, 0.08794, 0.08794]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_2.geometry} material={materials.PaletteMaterial003} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_4.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_5.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_6.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013_7.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Cube022.geometry} material={materials['Magnificent wood']} position={[3.18556, 4.2879, 1.83277]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.04287, -0.4789, -0.99824]} />
      <group position={[3.47452, 4.83262, 0.14511]} scale={0.08426}>
        <mesh castShadow receiveShadow geometry={nodes.Circle_1.geometry} material={materials.PaletteMaterial004} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_2.geometry} material={materials.PaletteMaterial005} />
        <mesh castShadow receiveShadow geometry={nodes.Circle_3.geometry} material={materials.PaletteMaterial006} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.shroomPotBookshelf.geometry} material={materials['Clay Base 01']} position={[3.43743, 4.92916, -1.86921]} scale={[0.10621, 0.09403, 0.10027]} />
      <group position={[3.20426, 3.99994, 2.61497]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00861}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere003.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere003_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.22435, 4.07088, 2.21676]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.01019}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere003.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere003_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.21822, 4.33378, 1.15938]} rotation={[0, 0, -Math.PI / 2]} scale={0.01312}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere008.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere008_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.24643, 4.66264, 1.47275]} rotation={[0, 0, -Math.PI / 2]} scale={0.01653}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere009.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere009_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.21276, 4.64922, 1.86975]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.01019}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere010.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere010_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.19595, 4.28194, 2.61684]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00656}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere012.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere012_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.21737, 4.4245, 2.48133]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00861}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere016.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere016_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.21707, 4.45701, 2.35133]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00861}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere017.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere017_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.21832, 4.15445, 2.46355]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00702}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere018.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere018_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.21788, 4.29919, 2.20498]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00861}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere019.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere019_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.19492, 4.35729, 2.15349]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00861}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere020.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere020_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.20247, 4.18452, 1.99964]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00702}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere023.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere023_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.20124, 4.01295, 1.89344]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.00702}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere024.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere024_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.22232, 4.46798, 1.86714]} rotation={[-0.27206, -0.04861, -1.73041]} scale={0.01019}>
        <mesh castShadow receiveShadow geometry={nodes.Sphere028.geometry} material={materials.PaletteMaterial001} />
        <mesh castShadow receiveShadow geometry={nodes.Sphere028_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.SM_Wood_doll.geometry} material={materials['Magnificent wood']} position={[3.45513, 4.23683, -0.83844]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes['3D_Lamborghini_Text_Logo002'].geometry} material={materials.PaletteMaterial002} position={[3.18274, 4.50822, 2.45234]} rotation={[1.81498, 0.09641, -1.58115]} scale={3.09965} />
      <mesh castShadow receiveShadow geometry={nodes.collar001.geometry} material={materials.bone} position={[3.4654, 5.30794, -0.22676]} rotation={[0, 1.57053, 0]} scale={0.32097} />
      <group position={[3.47261, 4.32278, -0.47133]} rotation={[0, 1.0701, 0]} scale={[2.53676, 2.54191, 1.33795]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube063.geometry} material={materials['Black metal']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube063_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube063_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube063_3.geometry} material={materials.PaletteMaterial007} />
        <mesh castShadow receiveShadow geometry={nodes.Cube063_4.geometry} material={materials['Black metal']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube063_5.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube063_6.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube063_7.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.40553, 4.24571, -1.99617]} rotation={[0, 0.82071, 0]} scale={2.00947}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder107.geometry} material={materials.DesertRoseSmallTex} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder107_1.geometry} material={materials['Clay Base 01']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder107_2.geometry} material={materials.stony_dirt_path} />
      </group>
      <group position={[3.62164, 4.25735, -1.1163]} rotation={[-0.07961, -0.62025, 0.88003]} scale={1.41786}>
        <mesh castShadow receiveShadow geometry={nodes.Circle047.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Circle047_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Circle047_2.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.29815, 4.8224, -0.73617]} scale={[1.39397, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube170.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube170_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube170_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube170_3.geometry} material={materials.PaletteMaterial008} />
        <mesh castShadow receiveShadow geometry={nodes.Cube170_4.geometry} material={materials.PaletteMaterial002} />
      </group>
      <group position={[3.43748, 5.00924, -1.86565]}>
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve.geometry} material={materials.PaletteMaterial009} />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve_1.geometry} material={materials['Stiel.003']} />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve_2.geometry} material={materials['Lammelleln.001']} />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve_3.geometry} material={materials['Stiel.004']} />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve_4.geometry} material={materials['Stiel.005']} />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve_5.geometry} material={materials['boden.001']} />
      </group>
      <group position={[3.41903, 4.83103, -0.36294]} scale={2.68371}>
        <mesh castShadow receiveShadow geometry={nodes.Cube187.geometry} material={materials.paper} />
        <mesh castShadow receiveShadow geometry={nodes.Cube187_1.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube187_2.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube187_3.geometry} material={materials.PaletteMaterial002} />
        <mesh castShadow receiveShadow geometry={nodes.Cube187_4.geometry} material={materials.PaletteMaterial002} />
      </group>
      <instancedMesh args={[nodes.Sphere005.geometry, materials.PaletteMaterial001, 6]} castShadow receiveShadow instanceMatrix={nodes.Sphere005.instanceMatrix} />
      <instancedMesh args={[nodes.Sphere005_1.geometry, materials.PaletteMaterial002, 6]} castShadow receiveShadow instanceMatrix={nodes.Sphere005_1.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/room_4-transformed.glb')
